[package]
name = "atomcad"
version = "0.1.0"
authors = ["Mark Friedenbach <mark@friedenbach.org>", "Lachlan Sneff <lachlan.sneff@gmail.com>"]
license = "MPL-2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/render",
    "crates/periodic-table",
    "crates/common",
]

[dependencies.render]
package = "atomcad-render"
path = "crates/render"
[dependencies.common]
package = "atomcad-common"
path = "crates/common"
[dependencies.periodic-table]
package = "atomcad-periodic-table"
path = "crates/periodic-table"

[dependencies]
futures = "0.3.28"
ultraviolet = "0.9.1"
log = "0.4.19"
lib3dmol = "0.4"
nom = "7.1.3"
winit = "0.28"

# macOS:
[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"

# web:
[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = "0.3.45"
wasm-bindgen-futures = "0.4.18"
console_error_panic_hook = "0.1.6"
console_log = "0.2"
