[package]
name = "atomcad"
version = { workspace = true }
publish = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }

[workspace.package]
version = "0.1.0"
publish = false
authors = ["Machine Phase Systems <hello@machinephase.systems>"]
edition = "2021"

[dependencies]
