[package]
name = "atomcad"
version = "0.1.0"
publish = false
authors = ["Machine Phase Systems <hello@machinephase.systems>"]
license = "MPL-2.0"
edition = "2021"

[workspace.dependencies]
bevy = { version = "0.14" }

# Enable a small amount of optimization for our code in debug mode:
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy):
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = { workspace = true }
bevy_asset_loader = { version = "0.21" }

# keep the following in sync with Bevy's dependencies
winit = { version = "0.30", default-features = false }
image = { version = "0.25", default-features = false }

[target.'cfg(target_family = "wasm")'.dependencies]
web-sys = { version = "0.3" }

[target.'cfg(target_family = "wasm")'.dev-dependencies]
wasm-bindgen-test = { version = "0.3" }

[build-dependencies]
embed-resource = "2"
