[package]
name = "atomcad"
version = "0.1.0"
authors = ["Lachlan Sneff <lachlan.sneff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "crates/render",
    "crates/periodic-table",
    "crates/common",
]

[dependencies.render]
package = "atomcad-render"
path = "crates/render/"
[dependencies.common]
package = "atomcad-common"
path = "crates/common/"
[dependencies.periodic-table]
package = "atomcad-periodic-table"
path = "crates/periodic-table"

[dependencies]
futures = "0.3.5"
ultraviolet = "0.7.0"
log = "0.4.11"
lib3dmol = "0.3.2"
nom = "5.1.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
winit = "0.22.2"
subscriber = { package = "wgpu-subscriber", version = "0.1" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
winit = { version = "0.22.2", features = ["web-sys"] }
web-sys = "0.3.45"
wasm-bindgen-futures = "0.4.18"
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"

# [patch."https://github.com/gfx-rs/wgpu".wgpu-core]
# git = "https://github.com/lachlansneff/wgpu"
# rev = "55dd333c2b1596b8f1317b4e7f5bc8cb95af4233"

# [patch."https://github.com/gfx-rs/wgpu".wgpu-types]
# git = "https://github.com/lachlansneff/wgpu"
# rev = "55dd333c2b1596b8f1317b4e7f5bc8cb95af4233"

# [patch.crates-io.gfx-backend-metal]
# git = "https://github.com/lachlansneff/gfx"
# rev = "e3e1e285170cdad7e100d7bf0b0833c00ea28dcd"

# [patch.crates-io.gfx-hal]
# git = "https://github.com/lachlansneff/gfx"
# rev = "e3e1e285170cdad7e100d7bf0b0833c00ea28dcd"

[patch."https://github.com/gfx-rs/wgpu-rs"]
wgpu = { git = "https://github.com/lachlansneff/wgpu-rs", rev = "8aee18961eb03afa59147d7493f413b73c5bea5d" }

[patch."https://github.com/gfx-rs/wgpu"]
wgpu-core = { git = "https://github.com/lachlansneff/wgpu", rev = "b84cfcb834cd3a447151fe9ebfb543ff558e2d76" }
wgpu-types = { git = "https://github.com/lachlansneff/wgpu", rev = "b84cfcb834cd3a447151fe9ebfb543ff558e2d76" }
#wgpu-types = { version = "0.6", path = "../wgpu/wgpu-types" }
#wgpu-core = { version = "0.6", path = "../wgpu/wgpu-core" }

[patch.crates-io]
gfx-hal = { git = "https://github.com/lachlansneff/gfx", rev = "01a81050eccc909428ab928c251ad8b1683fd45f" }
gfx-backend-vulkan = { git = "https://github.com/lachlansneff/gfx", rev = "01a81050eccc909428ab928c251ad8b1683fd45f" }
gfx-backend-empty = { git = "https://github.com/lachlansneff/gfx", rev = "01a81050eccc909428ab928c251ad8b1683fd45f" }
gfx-backend-metal = { git = "https://github.com/lachlansneff/gfx", rev = "01a81050eccc909428ab928c251ad8b1683fd45f" }

