[package]
name = "atomcad"
version = "0.1.0"
publish = false
authors = ["Machine Phase Systems <hello@machinephase.systems>"]
license = "MPL-2.0"
edition = "2021"
exclude = ["dist", "build", "assets", "credits"]

[workspace]
members = [
    "crates/common",
    "crates/molecule",
    "crates/periodic-table",
    "mobile"
]

[workspace.dependencies]
bevy = { version = "0.12", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_gltf",
    "bevy_pbr",
    "bevy_render",
    "bevy_scene",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "hdr",
    "ktx2",
    "png",
    "tonemapping_luts",
    "webgl2",
    "x11",
    "zstd",
] }
bevy_mod_picking = { version = "0.17", default-features = false, features = [
    "backend_raycast",
    "backend_bevy_ui",
    "backend_sprite",
    "highlight",
    "selection",
] }
common = { package = "atomcad-common", path = "crates/common" }
molecule = { package = "atomcad-molecule", path = "crates/molecule" }
periodic-table = { package = "atomcad-periodic-table", path = "crates/periodic-table" }
petgraph = { version = "0.6.4" }
serde = { version =  "1.0" }
static_assertions = { version = "1" }
ultraviolet = { version = "0.9" }

# Enable a small amount of optimization for our code in debug mode:
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy):
[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
codegen-units = 1

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[dependencies]
bevy = { workspace = true }
bevy_asset_loader = { version = "0.18" }
bevy_egui = { version = "0.23", default-features = false, features = [
    "open_url",
    "default_fonts"
] }
bevy_mod_picking = { workspace = true }
common = { workspace = true }
molecule = { workspace = true }
periodic-table = { workspace = true }
rand = { version = "0.8.3" }
smooth-bevy-cameras = { version = "0.10" }

# keep the following in sync with Bevy's dependencies
winit = { version = "0.28", default-features = false }
image = { version = "0.24", default-features = false }

[target.'cfg(target_family = "wasm")'.dependencies]
web-sys = { version = "0.3" }

[target.'cfg(target_family = "wasm")'.dev-dependencies]
wasm-bindgen-test = { version = "0.3" }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2.7"

[build-dependencies]
embed-resource = "1.4"
