[package]
name = "atomcad"
version = "0.1.0"
authors = [
    "Lachlan Sneff <lachlan@charted.space>",
    "Mark Friedenbach <mark@friedenbach.org>",
]
edition = "2018"

[features]
default = ["metrics"]
metrics = []

# Custom debug profile so it runs with
# reasonable performance.
[profile.dev]
opt-level = 2
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 16
rpath = false

[profile.release]
# Include symbols so that perf tools can do their thing.
debug = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# errors
thiserror = "1.0"
anyhow = "1.0"

# log
log = "0.4"
env_logger = "0.7"

# For event loop
winit = "0.22"

# For GPU
# wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", rev = "04db8c973c6c7bfbb5f89d3d18ef365d19d9af82" }
wgpu = "0.5.0"
gfx-memory = "=0.1.1"
bytemuck = "1.2"
glsl-layout = "0.3"

# For UI
# The iced crate is still very much a WIP, so we're pulling
# from a known commit in the github repo for the near future.
iced_winit = { git = "https://github.com/hecrj/iced.git", rev =  "33448508a524db6447b380cc236be6f0d5ca8a86" }
iced_wgpu = { git = "https://github.com/hecrj/iced.git", rev = "33448508a524db6447b380cc236be6f0d5ca8a86" }
# iced_winit = "0.1.0"
# iced_wgpu = "0.2.1"

# For matrix math
# ultraviolet = "0.4"
cgmath = "0.17.0"
arcball = "1.0.0"

futures = "0.3"
parking_lot = "0.10"

rand = "0.7"

[build-dependencies]
shaderc = "0.6"

# End of File
