[package]
name = "atomcad"
version = "0.1.0"
authors = [
    "Lachlan Sneff <lachlan@charted.space>",
    "Mark Friedenbach <mark@friedenbach.org>"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# errors
thiserror = "1.0"
anyhow = "1.0"

# log
log = "0.4"
env_logger = "0.7"

# For event loop
winit = "0.22"

# For GPU
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", rev = "04db8c973c6c7bfbb5f89d3d18ef365d19d9af82" }

# For UI
# iced_winit = { git = "https://github.com/hecrj/iced.git", rev = "fd7d9622e333a0a2cd5c2e8e6cc38cc09d7981e4" }
# iced_wgpu = { git = "https://github.com/hecrj/iced.git", rev = "fd7d9622e333a0a2cd5c2e8e6cc38cc09d7981e4" }

# For matrix math
nalgebra = "0.20.0"
nalgebra-glm = "0.6.0"

futures = "0.3"