[package]
name = "atomcad"
version = "0.1.0"
authors = ["Lachlan Sneff <lachlan.sneff@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git" }
wgpu-conveyor = "0.1.0"
futures = "0.3.5"
ultraviolet = "0.7.0"
static_assertions = "1.1.0"
rand = "0.7.3"
log = "0.4.11"
lib3dmol = "0.3.2"
hecs = "0.2.14"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
winit = "0.22.2"
subscriber = { package = "wgpu-subscriber", version = "0.1" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
winit = { version = "0.22.2", features = ["web-sys"] }
web-sys = "0.3.45"
wasm-bindgen-futures = "0.4.18"
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"

[build-dependencies]
shaderc = "0.6.2"

[patch.crates-io]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git" }
