[package]
name = "nanocad"
version = "0.1.0"
authors = ["Lachlan Sneff <lachlan.sneff@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# errors
thiserror = "1.0"
anyhow = "1.0"

# log
log = "0.4"
env_logger = "0.7"

# For event loop
winit = "0.22.0"

nalgebra = "0.20.0"
nalgebra-glm = "0.6.0"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", rev = "04db8c973c6c7bfbb5f89d3d18ef365d19d9af82" }

[dependencies.tokio]
version = "0.2"
features = ["rt-core", "rt-util", "stream", "time", "sync"]