[package]
name = "atomcad"
version = "0.1.0"
publish = false
authors = ["Machine Phase Systems <hello@machinephase.systems>"]
license = "MPL-2.0"
edition = "2021"
exclude = ["dist", "build", "assets", "credits"]

[workspace]
members = [ 
    "crates/app_config",
    "crates/common",
    "crates/molecule",
    "crates/periodic-table",
    "mobile"
]

[workspace.dependencies]
app_config = { package = "app_config", path = "crates/app_config"}
bevy = { version = "0.13", default-features = false, features = [
    "animation",
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_debug_stepping",
    "bevy_gltf",
    "bevy_pbr",
    "bevy_render",
    "bevy_scene",
    "bevy_sprite",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "hdr",
    "ktx2",
    "png",
    "tonemapping_luts",
    "webgl2",
    "x11",
    "zstd",
] }
bevy_mod_picking = { version = "0.18", default-features = false, features = [
    "backend_raycast",
    "backend_bevy_ui",
    "backend_sprite",
    "highlight",
    "selection",
] }
common = { package = "atomcad-common", path = "crates/common" }
directories = { version = "5" }
molecule = { package = "atomcad-molecule", path = "crates/molecule" }
periodic-table = { package = "atomcad-periodic-table", path = "crates/periodic-table" }
petgraph = { version = "0.6.4" }
rusqlite = { version = "0.30", features = ["bundled"]}
serde = { version =  "1.0" }
static_assertions = { version = "1" }
ultraviolet = { version = "0.9" }

[features]
sqlite-tracing = ["rusqlite/trace", "app_config/sqlite-tracing"]

# Enable a small amount of optimization for our code in debug mode:
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy):
[profile.dev.package."*"]
opt-level = 3

# This is used by trunk as it doesn't support custom profiles: https://github.com/trunk-rs/trunk/issues/605
# xbuild also uses this profile for building android AABs because I couldn't find a configuration for it
[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = true

# Profile for distribution
[profile.dist]
inherits = "release"
opt-level = 3
lto = true
codegen-units = 1
strip = true

[dependencies]
app_config = { workspace = true }
bevy = { workspace = true }
bevy_asset_loader = { version = "0.20" }
bevy_egui = { version = "0.26", default-features = false, features = [
    "open_url",
    "default_fonts"
] }
bevy_mod_picking = { workspace = true }
common = { workspace = true }
molecule = { workspace = true }
periodic-table = { workspace = true }
rand = { version = "0.8.3" }
rusqlite = { workspace = true, optional = true }
smooth-bevy-cameras = { version = "0.11" }

# keep the following in sync with Bevy's dependencies
winit = { version = "0.29", default-features = false }
image = { version = "0.24", default-features = false }

[target.'cfg(target_family = "wasm")'.dependencies]
web-sys = { version = "0.3" }

[target.'cfg(target_family = "wasm")'.dev-dependencies]
wasm-bindgen-test = { version = "0.3" }

[target.'cfg(target_os = "linux")'.dependencies]
directories = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
directories = { workspace = true }
objc = "0.2.7"

[target.'cfg(target_os = "windows")'.dependencies]
directories = { workspace = true }

# Specificlly exclude rusqlite from android and wasm32 builds
[target.'cfg(not(any(target_os = "android", target_arch = "wasm32", target = "wasm32-unknown-unknown")))'.dependencies]
rusqlite = { workspace = true }

[build-dependencies]
embed-resource = "1"
