[package]
name = "atomcad-render"
version = "0.1.0"
authors = ["Lachlan Sneff <lachlan.sneff@gmail.com>"]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.common]
package = "atomcad-common"
path = "../common"

[dependencies.periodic-table]
package = "atomcad-periodic-table"
path = "../periodic-table"

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git" }
wgpu-conveyor = "0.1.0"
futures = "0.3.5"
ultraviolet = "0.7.0"
static_assertions = "1"
log = "0.4.11"
winit = "0.22.2"
indexmap = "1.6"

[build-dependencies]
shaderc = "0.6.2"
