[package]
name = "atomcad-render"
version = "0.1.0"
authors = ["Mark Friedenbach <mark@friedenbach.org>", "Lachlan Sneff <lachlan.sneff@gmail.com>"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.common]
package = "atomcad-common"
path = "../common"

[dependencies.periodic-table]
package = "atomcad-periodic-table"
path = "../periodic-table"

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git" }
futures = "0.3.28"
ultraviolet = "0.9.1"
static_assertions = "1"
log = "0.4.19"
winit = "0.27.0"
indexmap = "1.6"
parking_lot =  "0.11"

[build-dependencies]
shaderc = "0.8.2"
