//! Phase 5 of `doc/design_error_management.md` (D7) — root-cause origin links.
//!
//! Whenever a resolved wire value is an `Error`, the evaluator records an
//! **origin link** for the consumer: the jump-ready global address of the node
//! the error came from. An errored node with no link is a **root cause**; every
//! other errored node is *derived* and collapses behind its root in the panel,
//! so one failure produces one row instead of one row per node in its
//! downstream cone. Links cross custom-network boundaries (the two wrap sites
//! record the boundary hop explicitly), are pass-scoped (regenerated by every
//! refresh), and — where they are copied into a long-lived snapshot — follow
//! D6's key lifecycle when a network is renamed.

use atomcad_structure_designer::data_type::DataType;
use atomcad_structure_designer::eval_errors::{ErrorAddress, ErrorOrigin};
use atomcad_structure_designer::evaluator::network_evaluator::{
    NetworkEvaluationContext, NetworkEvaluator, NetworkStackElement,
};
use atomcad_structure_designer::node_network::{NodeRef, ValidationError};
use atomcad_structure_designer::nodes::expr::{ExprData, ExprParameter};
use atomcad_structure_designer::structure_designer::StructureDesigner;
use glam::f64::DVec2;
use rust_lib_flutter_cad::api::structure_designer::structure_designer_api_types::{
    APIErrorSource, APINetworkWithValidationErrors, APIValidationError,
};

// ============================================================================
// Helpers
// ============================================================================

fn setup_designer_with_network(network_name: &str) -> StructureDesigner {
    let mut designer = StructureDesigner::new();
    designer.add_node_network(network_name);
    designer.set_active_node_network_name(Some(network_name.to_string()));
    designer
}

fn full_refresh(designer: &mut StructureDesigner) {
    designer.mark_full_refresh();
    let changes = designer.get_pending_changes();
    designer.refresh(&changes);
}

fn validate_and_refresh(designer: &mut StructureDesigner) {
    designer.validate_active_network();
    full_refresh(designer);
}

/// Add an `expr` node to the **active** network with the given expression and
/// parameter names (all `Int`). A parameter left unwired makes the node fail at
/// runtime with a clean localized "missing input" error — the canonical root
/// cause used throughout this file.
fn add_expr(designer: &mut StructureDesigner, expression: &str, params: &[&str]) -> u64 {
    let id = designer.add_node_scoped(&[], "expr", DVec2::ZERO, None);
    set_expr_data(designer, &[], id, expression, params);
    id
}

fn set_expr_data(
    designer: &mut StructureDesigner,
    scope_path: &[u64],
    node_id: u64,
    expression: &str,
    params: &[&str],
) {
    let mut data = ExprData {
        parameters: params
            .iter()
            .map(|name| ExprParameter {
                id: None,
                name: name.to_string(),
                data_type: DataType::Int,
                data_type_str: None,
            })
            .collect(),
        expression: expression.to_string(),
        expr: None,
        error: None,
        output_type: None,
    };
    let _ = data.parse_and_validate(0);
    designer.set_node_network_data_scoped(scope_path, node_id, Box::new(data));
}

/// The unified error list of one network (`APIValidationError` is not `Clone`,
/// so the entry is taken by value out of the freshly built list).
fn errors_of(designer: &StructureDesigner, network_name: &str) -> Vec<APIValidationError> {
    let networks: Vec<APINetworkWithValidationErrors> =
        rust_lib_flutter_cad::api::structure_designer::view_builders::get_node_networks_with_errors(
            designer,
        );
    networks
        .into_iter()
        .find(|n| n.name == network_name)
        .unwrap_or_else(|| panic!("network '{network_name}' present in the error list"))
        .validation_errors
}

/// The rows the panel lists at top level: everything that is not a *derived*
/// entry (derived rows collapse behind their root's row).
fn top_level_rows(errors: &[APIValidationError]) -> Vec<&APIValidationError> {
    errors.iter().filter(|e| e.root_cause.is_none()).collect()
}

fn row_for_node<'a>(
    errors: &'a [APIValidationError],
    node_id: u64,
    source: APIErrorSource,
) -> &'a APIValidationError {
    errors
        .iter()
        .find(|e| e.node_id == Some(node_id) && e.source == source)
        .unwrap_or_else(|| {
            panic!(
                "no {:?} row for node {}; rows: {:?}",
                source,
                node_id,
                errors
                    .iter()
                    .map(|e| (e.node_id, e.source, &e.error_text))
                    .collect::<Vec<_>>()
            )
        })
}

// ============================================================================
// Same-network chains
// ============================================================================

/// A chain of three nodes whose head fails yields **one** top-level row (the
/// head) and two derived entries, each carrying the chain's root — so the panel
/// shows one problem, not its three symptoms. Each derived entry's link points
/// one hop upstream, which is what makes the walk to the root exact.
#[test]
fn chain_of_three_has_one_root_and_derived_entries() {
    let mut designer = setup_designer_with_network("main");
    let head = add_expr(&mut designer, "x + 1", &["x"]); // `x` left unwired → fails
    let middle = add_expr(&mut designer, "y + 1", &["y"]);
    let tail = add_expr(&mut designer, "z + 1", &["z"]);
    designer.connect_nodes(head, 0, middle, 0);
    designer.connect_nodes(middle, 0, tail, 0);
    designer.set_node_display(tail, true);
    validate_and_refresh(&mut designer);

    let errors = errors_of(&designer, "main");
    let roots = top_level_rows(&errors);
    assert_eq!(
        roots.len(),
        1,
        "one failure ⇒ one top-level row; got {:?}",
        roots
            .iter()
            .map(|e| (e.node_id, &e.error_text))
            .collect::<Vec<_>>()
    );
    assert_eq!(roots[0].node_id, Some(head));

    for derived_id in [middle, tail] {
        let row = row_for_node(&errors, derived_id, APIErrorSource::Evaluation);
        let root = row
            .root_cause
            .as_ref()
            .unwrap_or_else(|| panic!("node {derived_id} must be derived"));
        assert_eq!(root.node_id, head, "the walk ends at the chain's head");
        assert_eq!(root.host_network, "main");
        assert!(root.scope_path.is_empty());
        assert!(
            !root.error_text.is_empty(),
            "the root's own text travels with the link (transient landing surface)"
        );
    }
}

/// A derived chain routinely terminates at a **poisoned** node (blocking
/// validation error → skip-and-synthesize). The collapse parent is the *node*,
/// so the derived entries hang off its **validation** row; the synthesized eval
/// entry stays deduped away (D8) and no derived entry is left orphaned at top
/// level.
#[test]
fn poisoned_root_collapses_behind_its_validation_row() {
    let mut designer = setup_designer_with_network("main");
    let head = add_expr(&mut designer, "1 + 1", &[]);
    let middle = add_expr(&mut designer, "y + 1", &["y"]);
    designer.connect_nodes(head, 0, middle, 0);
    designer.set_node_display(middle, true);
    designer.validate_active_network();

    // Attribute a blocking validation error to the head (the shape any
    // cone-poisoning rule produces — e.g. a bare `relax`'s unresolved output).
    designer
        .node_type_registry
        .node_networks
        .get_mut("main")
        .unwrap()
        .validation_errors
        .push(ValidationError::new(
            "head is broken".to_string(),
            Some(head),
        ));
    full_refresh(&mut designer);

    let errors = errors_of(&designer, "main");
    let roots = top_level_rows(&errors);
    assert_eq!(
        roots.len(),
        1,
        "exactly one top-level row: the poisoned node's validation error; got {:?}",
        roots
            .iter()
            .map(|e| (e.node_id, e.source, &e.error_text))
            .collect::<Vec<_>>()
    );
    assert_eq!(roots[0].source, APIErrorSource::Validation);
    assert_eq!(roots[0].node_id, Some(head));

    // The poisoned node contributes no eval row (D8), and the downstream entry
    // collapses behind the node it addresses.
    assert!(
        !errors
            .iter()
            .any(|e| e.node_id == Some(head) && e.source == APIErrorSource::Evaluation),
        "the synthesized entry must stay deduped away"
    );
    let derived = row_for_node(&errors, middle, APIErrorSource::Evaluation);
    let root = derived.root_cause.as_ref().expect("middle is derived");
    assert_eq!(root.node_id, head);
}

/// Two independent failures are two independent problems: each is its own
/// top-level row, and each downstream cone collapses behind its own root.
#[test]
fn independent_failures_are_separate_roots() {
    let mut designer = setup_designer_with_network("main");
    let source_a = add_expr(&mut designer, "x + 1", &["x"]);
    let sink_a = add_expr(&mut designer, "p + 1", &["p"]);
    let source_b = add_expr(&mut designer, "y + 1", &["y"]);
    let sink_b = add_expr(&mut designer, "q + 1", &["q"]);
    designer.connect_nodes(source_a, 0, sink_a, 0);
    designer.connect_nodes(source_b, 0, sink_b, 0);
    designer.set_node_display(sink_a, true);
    designer.set_node_display(sink_b, true);
    validate_and_refresh(&mut designer);

    let errors = errors_of(&designer, "main");
    let mut root_ids: Vec<u64> = top_level_rows(&errors)
        .iter()
        .filter_map(|e| e.node_id)
        .collect();
    root_ids.sort_unstable();
    let mut expected = vec![source_a, source_b];
    expected.sort_unstable();
    assert_eq!(root_ids, expected, "both sources are top-level roots");

    assert_eq!(
        row_for_node(&errors, sink_a, APIErrorSource::Evaluation)
            .root_cause
            .as_ref()
            .map(|r| r.node_id),
        Some(source_a)
    );
    assert_eq!(
        row_for_node(&errors, sink_b, APIErrorSource::Evaluation)
            .root_cause
            .as_ref()
            .map(|r| r.node_id),
        Some(source_b)
    );
}

/// Links are recorded at **wire resolution**, so they cover consumers that
/// merely pass an upstream error through — a lazy selector like `if` never
/// wraps the error in text of its own, yet its entry is still classified as
/// derived and points at the failure it forwarded.
#[test]
fn origins_are_recorded_for_a_pass_through_consumer() {
    let mut designer = setup_designer_with_network("main");
    let cond = designer.add_node("bool", DVec2::ZERO);
    let failing = add_expr(&mut designer, "x + 1", &["x"]);
    let selector = designer.add_node("if", DVec2::new(200.0, 0.0));
    designer.connect_nodes(cond, 0, selector, 0);
    // Both branches fail, so the link is recorded whichever one `if` takes.
    designer.connect_nodes(failing, 0, selector, 1);
    designer.connect_nodes(failing, 0, selector, 2);
    designer.set_node_display(selector, true);
    validate_and_refresh(&mut designer);

    let errors = errors_of(&designer, "main");
    let roots = top_level_rows(&errors);
    assert_eq!(
        roots.len(),
        1,
        "the forwarded error is one problem, not two; got {:?}",
        roots
            .iter()
            .map(|e| (e.node_id, &e.error_text))
            .collect::<Vec<_>>()
    );
    assert_eq!(roots[0].node_id, Some(failing));
    assert_eq!(
        row_for_node(&errors, selector, APIErrorSource::Evaluation)
            .root_cause
            .as_ref()
            .map(|r| r.node_id),
        Some(failing),
        "a pass-through consumer is derived, like a wrapping one"
    );
}

// ============================================================================
// The recording contract (evaluator level)
// ============================================================================

/// One link **per distinct failing input**, in input-pin order, deduped by
/// address. A single-slot value would silently lose chains: a consumer with two
/// independently errored inputs must keep a link to each. (Most nodes early-out
/// on their first errored input, so this contract is exercised directly against
/// `evaluate_arg` — the choke point that records it.)
#[test]
fn each_failing_input_records_its_own_link_in_pin_order() {
    let mut designer = setup_designer_with_network("main");
    let source_x = add_expr(&mut designer, "a + 1", &["a"]); // fails
    let source_y = add_expr(&mut designer, "b + 1", &["b"]); // fails
    let sink = add_expr(&mut designer, "x + y", &["x", "y"]);
    designer.connect_nodes(source_x, 0, sink, 0);
    designer.connect_nodes(source_y, 0, sink, 1);
    designer.validate_active_network();

    let registry = &designer.node_type_registry;
    let network = registry.node_networks.get("main").unwrap();
    let evaluator = NetworkEvaluator::new();
    let mut context = NetworkEvaluationContext::new();
    let network_stack = vec![NetworkStackElement::root(network)];
    // Resolve both pins, as a node tolerating its first errored input would.
    for param_index in 0..2 {
        let _ = evaluator.evaluate_arg(&network_stack, sink, registry, &mut context, param_index);
    }
    // Re-resolving pin 0 must not add a second link for the same address.
    let _ = evaluator.evaluate_arg(&network_stack, sink, registry, &mut context, 0);

    let links = context
        .node_error_origins
        .get(&NodeRef::top(sink))
        .expect("the sink recorded its origins");
    assert_eq!(
        links
            .iter()
            .map(|link| link.address.node_id)
            .collect::<Vec<_>>(),
        vec![source_x, source_y],
        "one link per failing input, in input-pin order, deduped by address"
    );
    assert_eq!(links[0].source_ref, NodeRef::top(source_x));
    assert_eq!(links[0].address.host_network, "main");
}

/// A wire inside a zone body addresses its source with the **body's scope
/// path**: the address's `scope_path` is the chain of zone-body hops since the
/// last network hop, read off the live network stack (the only place that
/// distinguishes a body hop from a custom-network hop).
#[test]
fn body_wire_source_carries_the_body_scope_path() {
    let mut designer = setup_designer_with_network("main");
    let map_id = designer.add_node("map", DVec2::ZERO);
    let body_source = designer.add_node_scoped(&[map_id], "expr", DVec2::ZERO, None);
    set_expr_data(&mut designer, &[map_id], body_source, "a + 1", &["a"]);
    let body_sink = designer.add_node_scoped(&[map_id], "expr", DVec2::new(200.0, 0.0), None);
    set_expr_data(&mut designer, &[map_id], body_sink, "b + 1", &["b"]);
    designer.connect_nodes_scoped(&[map_id], body_source, 0, body_sink, 0);
    designer.validate_active_network();

    let registry = &designer.node_type_registry;
    let network = registry.node_networks.get("main").unwrap();
    let body = network.nodes[&map_id].zone.as_deref().unwrap();
    let evaluator = NetworkEvaluator::new();
    let mut context = NetworkEvaluationContext::new();
    context.push_eval_scope(map_id);
    let network_stack = vec![
        NetworkStackElement::root(network),
        NetworkStackElement::body_static(body, map_id),
    ];
    let _ = evaluator.evaluate_arg(&network_stack, body_sink, registry, &mut context, 0);

    let links = context
        .node_error_origins
        .get(&NodeRef::scoped(&[map_id], body_sink))
        .expect("the body sink recorded its origin");
    assert_eq!(
        links,
        &vec![ErrorOrigin {
            address: ErrorAddress {
                host_network: "main".to_string(),
                scope_path: vec![map_id],
                node_id: body_source,
            },
            source_ref: NodeRef::scoped(&[map_id], body_source),
        }],
        "a body wire's source is addressed inside the body, in its own network"
    );
}

// ============================================================================
// Cross-network chains
// ============================================================================

/// A failure inside a custom network surfaces in the *using* network as a
/// derived entry on the instance, whose root addresses the offending node
/// **inside the child** — and that root joins the list as its own top-level row
/// with a provenance qualifier, so the collapse parent is always present.
#[test]
fn cross_network_root_cause_is_addressed_in_the_child() {
    let mut designer = StructureDesigner::new();
    designer.add_node_network("child");
    designer.set_active_node_network_name(Some("child".to_string()));
    let child_expr = add_expr(&mut designer, "x + 1", &["x"]); // fails inside the child
    assert!(designer.set_return_node_id(Some(child_expr)));
    validate_and_refresh(&mut designer);

    designer.add_node_network("main");
    designer.set_active_node_network_name(Some("main".to_string()));
    let instance = designer.add_node("child", DVec2::ZERO);
    designer.set_node_display(instance, true);
    validate_and_refresh(&mut designer);

    let errors = errors_of(&designer, "main");

    // The instance is derived — its boundary link points into the child.
    let instance_row = row_for_node(&errors, instance, APIErrorSource::Evaluation);
    let root = instance_row
        .root_cause
        .as_ref()
        .expect("the instance's error is derived from the child's failure");
    assert_eq!(root.host_network, "child");
    assert_eq!(root.node_id, child_expr);
    assert!(root.scope_path.is_empty());

    // ...and the root itself is listed once, addressed in the child.
    let roots = top_level_rows(&errors);
    assert_eq!(
        roots.len(),
        1,
        "one problem ⇒ one top-level row; got {:?}",
        roots
            .iter()
            .map(|e| (&e.host_network, e.node_id, &e.error_text))
            .collect::<Vec<_>>()
    );
    assert_eq!(roots[0].host_network.as_deref(), Some("child"));
    assert_eq!(roots[0].node_id, Some(child_expr));
    assert_eq!(
        roots[0].body_qualifier.as_deref(),
        Some("in child"),
        "a cross-network row names its host network as provenance"
    );

    // "Go to root cause" on the instance resolves to the same address.
    let jump = rust_lib_flutter_cad::api::structure_designer::view_builders::get_node_root_cause(
        &designer,
        &[],
        instance,
    )
    .expect("the instance has a navigable root cause");
    assert_eq!(jump.host_network, "child");
    assert_eq!(jump.node_id, child_expr);
    assert!(!jump.node_label.is_empty());
}

/// Renaming a network rewrites the network names embedded in stored jump
/// addresses (D6 key lifecycle): the long-lived snapshot outlives the refresh
/// that produced it, so a stale name would jump nowhere.
#[test]
fn rename_rewrites_stored_root_cause_host_network() {
    let mut designer = StructureDesigner::new();
    designer.add_node_network("child");
    designer.set_active_node_network_name(Some("child".to_string()));
    let child_expr = add_expr(&mut designer, "x + 1", &["x"]);
    assert!(designer.set_return_node_id(Some(child_expr)));
    validate_and_refresh(&mut designer);

    designer.add_node_network("main");
    designer.set_active_node_network_name(Some("main".to_string()));
    let instance = designer.add_node("child", DVec2::ZERO);
    designer.set_node_display(instance, true);
    validate_and_refresh(&mut designer);

    // Leave "main" so its rows come from the long-lived snapshot, then rename
    // the network its addresses point at.
    designer.add_node_network("other");
    designer.set_active_node_network_name(Some("other".to_string()));
    validate_and_refresh(&mut designer);
    assert!(designer.rename_node_network("child", "kid"));

    let errors = errors_of(&designer, "main");
    let roots = top_level_rows(&errors);
    assert_eq!(
        roots.len(),
        1,
        "the cross-network row survives the rename (its host was rewritten)"
    );
    assert_eq!(roots[0].host_network.as_deref(), Some("kid"));
    assert_eq!(
        row_for_node(&errors, instance, APIErrorSource::Evaluation)
            .root_cause
            .as_ref()
            .map(|r| r.host_network.clone()),
        Some("kid".to_string()),
        "the derived row's root pointer follows the rename too"
    );
}

// ============================================================================
// Lifetime
// ============================================================================

/// Links are pass-scoped: a second refresh regenerates them (no accumulation),
/// and fixing the root cause clears the whole chain — root row and derived
/// entries alike — in one step.
#[test]
fn links_are_regenerated_by_every_pass() {
    let mut designer = setup_designer_with_network("main");
    let head = add_expr(&mut designer, "x + 1", &["x"]);
    let tail = add_expr(&mut designer, "z + 1", &["z"]);
    designer.connect_nodes(head, 0, tail, 0);
    designer.set_node_display(tail, true);
    validate_and_refresh(&mut designer);

    let before = errors_of(&designer, "main").len();
    full_refresh(&mut designer);
    assert_eq!(
        errors_of(&designer, "main").len(),
        before,
        "a second pass replaces the links, it does not accumulate them"
    );

    // Fix the root cause → the entire chain clears.
    set_expr_data(&mut designer, &[], head, "1 + 1", &[]);
    validate_and_refresh(&mut designer);
    assert!(
        errors_of(&designer, "main").is_empty(),
        "fixing the root clears the root row and every derived entry"
    );
}
