[package]
name = "atomcad-keyboard"
version = { workspace = true }
publish = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
# Utilities
bitflags = "2.6"
