//! Tests for `apply_supercell`: validates site/bond count scaling, crystal-field
//! preservation (atom-set equivalence in real space), bond fidelity, motif
//! offset handling, matrix composition, and error paths.

use glam::f64::DVec3;
use glam::i32::IVec3;
use rust_lib_flutter_cad::crystolecule::crystolecule_constants::DIAMOND_UNIT_CELL_SIZE_ANGSTROM;
use rust_lib_flutter_cad::crystolecule::motif::{Motif, Site};
use rust_lib_flutter_cad::crystolecule::structure::Structure;
use rust_lib_flutter_cad::crystolecule::supercell::{
    MAX_SUPERCELL_SITES, SupercellError, apply_supercell,
};
use rust_lib_flutter_cad::crystolecule::unit_cell_struct::UnitCellStruct;

const IDENTITY: [[i32; 3]; 3] = [[1, 0, 0], [0, 1, 0], [0, 0, 1]];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/// Single-atom simple-cubic carbon structure with a tunable lattice parameter.
/// Used for tests where the zincblende motif would obscure the effect of `M`.
fn simple_cubic_carbon(a: f64) -> Structure {
    let lattice_vecs = UnitCellStruct::new(
        DVec3::new(a, 0.0, 0.0),
        DVec3::new(0.0, a, 0.0),
        DVec3::new(0.0, 0.0, a),
    );
    let motif = Motif {
        parameters: vec![],
        sites: vec![Site {
            atomic_number: 6,
            position: DVec3::ZERO,
        }],
        bonds: vec![],
        bonds_by_site1_index: vec![vec![]],
        bonds_by_site2_index: vec![vec![]],
    };
    Structure {
        lattice_vecs,
        motif,
        motif_offset: DVec3::ZERO,
    }
}

/// Face-centered cubic primitive: one atom per cell, with primitive basis
/// vectors that span a conventional cube of side `a`. Applying the standard
/// primitive→conventional matrix gives a 4-atom FCC conventional cell.
fn fcc_primitive(a: f64) -> Structure {
    let half = a * 0.5;
    let lattice_vecs = UnitCellStruct::new(
        DVec3::new(0.0, half, half),
        DVec3::new(half, 0.0, half),
        DVec3::new(half, half, 0.0),
    );
    let motif = Motif {
        parameters: vec![],
        sites: vec![Site {
            atomic_number: 6,
            position: DVec3::ZERO,
        }],
        bonds: vec![],
        bonds_by_site1_index: vec![vec![]],
        bonds_by_site2_index: vec![vec![]],
    };
    Structure {
        lattice_vecs,
        motif,
        motif_offset: DVec3::ZERO,
    }
}

/// Enumerates the real-space (position, atomic_number) pairs generated by the
/// crystal field of `structure` over the cell range `[cell_min, cell_max]`
/// inclusive, then keeps only those whose position lies in the half-open AABB
/// `[aabb_min, aabb_max)`. This is the hand-rolled equivalent of the
/// `materialize` node for a cuboid region — the design doc's "crystal_field"
/// semantics expressed as a concrete finite set.
fn enumerate_crystal_field_in_aabb(
    structure: &Structure,
    cell_min: IVec3,
    cell_max: IVec3,
    aabb_min: DVec3,
    aabb_max: DVec3,
) -> Vec<(DVec3, i16)> {
    let uc = &structure.lattice_vecs;
    let mut atoms = Vec::new();
    for pz in cell_min.z..=cell_max.z {
        for py in cell_min.y..=cell_max.y {
            for px in cell_min.x..=cell_max.x {
                let cell = IVec3::new(px, py, pz).as_dvec3();
                for site in &structure.motif.sites {
                    let frac = cell + structure.motif_offset + site.position;
                    let real = uc.dvec3_lattice_to_real(&frac);
                    if real.x >= aabb_min.x
                        && real.x < aabb_max.x
                        && real.y >= aabb_min.y
                        && real.y < aabb_max.y
                        && real.z >= aabb_min.z
                        && real.z < aabb_max.z
                    {
                        atoms.push((real, site.atomic_number));
                    }
                }
            }
        }
    }
    atoms
}

/// Enumerates bonds in real space as canonically-ordered endpoint pairs. Each
/// bond is produced once per cell in `[cell_min, cell_max]`, endpoint 1 being
/// the site_1 copy in that cell. A bond is kept iff both endpoints lie in
/// `[aabb_min, aabb_max)`.
fn enumerate_bonds_in_aabb(
    structure: &Structure,
    cell_min: IVec3,
    cell_max: IVec3,
    aabb_min: DVec3,
    aabb_max: DVec3,
) -> Vec<(DVec3, DVec3, i32)> {
    let uc = &structure.lattice_vecs;
    let mut bonds = Vec::new();
    for bond in &structure.motif.bonds {
        let s1 = &structure.motif.sites[bond.site_1.site_index];
        let s2 = &structure.motif.sites[bond.site_2.site_index];
        for pz in cell_min.z..=cell_max.z {
            for py in cell_min.y..=cell_max.y {
                for px in cell_min.x..=cell_max.x {
                    let cell = IVec3::new(px, py, pz).as_dvec3();
                    let p1_frac = cell + structure.motif_offset + s1.position;
                    let p2_frac = cell
                        + bond.site_2.relative_cell.as_dvec3()
                        + structure.motif_offset
                        + s2.position;
                    let p1 = uc.dvec3_lattice_to_real(&p1_frac);
                    let p2 = uc.dvec3_lattice_to_real(&p2_frac);
                    let in_box = |p: DVec3| {
                        p.x >= aabb_min.x
                            && p.x < aabb_max.x
                            && p.y >= aabb_min.y
                            && p.y < aabb_max.y
                            && p.z >= aabb_min.z
                            && p.z < aabb_max.z
                    };
                    if in_box(p1) && in_box(p2) {
                        let (a, b) = canonical_pair(p1, p2);
                        bonds.push((a, b, bond.multiplicity));
                    }
                }
            }
        }
    }
    bonds
}

fn canonical_pair(a: DVec3, b: DVec3) -> (DVec3, DVec3) {
    // Lex order on (x, y, z). NaN is impossible for our inputs.
    let a_lt_b = (a.x, a.y, a.z) < (b.x, b.y, b.z);
    if a_lt_b { (a, b) } else { (b, a) }
}

fn sort_atoms(mut atoms: Vec<(DVec3, i16)>) -> Vec<(DVec3, i16)> {
    atoms.sort_by(|x, y| {
        x.0.x
            .partial_cmp(&y.0.x)
            .unwrap()
            .then(x.0.y.partial_cmp(&y.0.y).unwrap())
            .then(x.0.z.partial_cmp(&y.0.z).unwrap())
            .then(x.1.cmp(&y.1))
    });
    atoms
}

fn sort_bonds(mut bonds: Vec<(DVec3, DVec3, i32)>) -> Vec<(DVec3, DVec3, i32)> {
    bonds.sort_by(|x, y| {
        x.0.x
            .partial_cmp(&y.0.x)
            .unwrap()
            .then(x.0.y.partial_cmp(&y.0.y).unwrap())
            .then(x.0.z.partial_cmp(&y.0.z).unwrap())
            .then(x.1.x.partial_cmp(&y.1.x).unwrap())
            .then(x.1.y.partial_cmp(&y.1.y).unwrap())
            .then(x.1.z.partial_cmp(&y.1.z).unwrap())
            .then(x.2.cmp(&y.2))
    });
    bonds
}

fn assert_atom_sets_equal(a: &[(DVec3, i16)], b: &[(DVec3, i16)], tol: f64) {
    assert_eq!(
        a.len(),
        b.len(),
        "atom set sizes differ: {} vs {}",
        a.len(),
        b.len()
    );
    for (i, (pa, pb)) in a.iter().zip(b.iter()).enumerate() {
        assert_eq!(
            pa.1, pb.1,
            "atomic_number differs at index {}: {} vs {}",
            i, pa.1, pb.1
        );
        assert!(
            (pa.0 - pb.0).length() < tol,
            "position differs at index {}: {:?} vs {:?}",
            i,
            pa.0,
            pb.0
        );
    }
}

fn assert_bond_sets_equal(a: &[(DVec3, DVec3, i32)], b: &[(DVec3, DVec3, i32)], tol: f64) {
    assert_eq!(
        a.len(),
        b.len(),
        "bond set sizes differ: {} vs {}",
        a.len(),
        b.len()
    );
    for (i, (ba, bb)) in a.iter().zip(b.iter()).enumerate() {
        assert_eq!(
            ba.2, bb.2,
            "bond multiplicity differs at index {}: {} vs {}",
            i, ba.2, bb.2
        );
        assert!(
            (ba.0 - bb.0).length() < tol,
            "bond endpoint 1 differs at index {}: {:?} vs {:?}",
            i,
            ba.0,
            bb.0
        );
        assert!(
            (ba.1 - bb.1).length() < tol,
            "bond endpoint 2 differs at index {}: {:?} vs {:?}",
            i,
            ba.1,
            bb.1
        );
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn identity_matrix_preserves_structure() {
    let s = Structure::diamond();
    let s2 = apply_supercell(&s, &IDENTITY).unwrap();
    assert!(s.is_approximately_equal(&s2));
}

#[test]
fn diagonal_2_2_2_on_diamond_scales_site_and_bond_counts() {
    let s = Structure::diamond();
    let m = [[2, 0, 0], [0, 2, 0], [0, 0, 2]];
    let s2 = apply_supercell(&s, &m).unwrap();

    assert_eq!(s2.motif.sites.len(), s.motif.sites.len() * 8);
    assert_eq!(s2.motif.bonds.len(), s.motif.bonds.len() * 8);

    let expected_len = DIAMOND_UNIT_CELL_SIZE_ANGSTROM * 2.0;
    let uc = &s2.lattice_vecs;
    assert!((uc.cell_length_a - expected_len).abs() < 1e-9);
    assert!((uc.cell_length_b - expected_len).abs() < 1e-9);
    assert!((uc.cell_length_c - expected_len).abs() < 1e-9);
    assert!(uc.is_approximately_cubic());

    // The precomputed per-site bond indices should cover every bond exactly
    // once on each side — matches how the motif parser builds them.
    let sum_site1: usize = s2.motif.bonds_by_site1_index.iter().map(|v| v.len()).sum();
    let sum_site2: usize = s2.motif.bonds_by_site2_index.iter().map(|v| v.len()).sum();
    assert_eq!(sum_site1, s2.motif.bonds.len());
    assert_eq!(sum_site2, s2.motif.bonds.len());
}

#[test]
fn diagonal_2_2_2_on_single_atom_motif_emits_eight_sites_at_half_integers() {
    let s = simple_cubic_carbon(3.0);
    let m = [[2, 0, 0], [0, 2, 0], [0, 0, 2]];
    let s2 = apply_supercell(&s, &m).unwrap();

    assert_eq!(s2.motif.sites.len(), 8);

    // Expected fractional coords in the new basis: all combinations of {0, 0.5}³.
    let mut actual: Vec<[f64; 3]> = s2
        .motif
        .sites
        .iter()
        .map(|s| [s.position.x, s.position.y, s.position.z])
        .collect();
    actual.sort_by(|a, b| {
        a[0].partial_cmp(&b[0])
            .unwrap()
            .then(a[1].partial_cmp(&b[1]).unwrap())
            .then(a[2].partial_cmp(&b[2]).unwrap())
    });

    let expected: Vec<[f64; 3]> = vec![
        [0.0, 0.0, 0.0],
        [0.0, 0.0, 0.5],
        [0.0, 0.5, 0.0],
        [0.0, 0.5, 0.5],
        [0.5, 0.0, 0.0],
        [0.5, 0.0, 0.5],
        [0.5, 0.5, 0.0],
        [0.5, 0.5, 0.5],
    ];
    for (a, e) in actual.iter().zip(expected.iter()) {
        for k in 0..3 {
            assert!(
                (a[k] - e[k]).abs() < 1e-12,
                "coord mismatch: got {:?}, want {:?}",
                a,
                e
            );
        }
    }
}

#[test]
fn fcc_primitive_to_conventional_produces_four_sites_and_cubic_lattice() {
    let a = 4.0;
    let s = fcc_primitive(a);
    // Standard primitive-to-conventional matrix; det = 4.
    let m = [[-1, 1, 1], [1, -1, 1], [1, 1, -1]];
    let s2 = apply_supercell(&s, &m).unwrap();

    assert_eq!(s2.motif.sites.len(), 4);

    // New lattice should be the cubic conventional cell of side `a`.
    assert!(s2.lattice_vecs.is_approximately_cubic());
    assert!((s2.lattice_vecs.cell_length_a - a).abs() < 1e-9);
    assert!((s2.lattice_vecs.cell_length_b - a).abs() < 1e-9);
    assert!((s2.lattice_vecs.cell_length_c - a).abs() < 1e-9);

    // Expected fractional coords in the conventional basis.
    let mut actual: Vec<[f64; 3]> = s2
        .motif
        .sites
        .iter()
        .map(|st| [st.position.x, st.position.y, st.position.z])
        .collect();
    actual.sort_by(|a, b| {
        a[0].partial_cmp(&b[0])
            .unwrap()
            .then(a[1].partial_cmp(&b[1]).unwrap())
            .then(a[2].partial_cmp(&b[2]).unwrap())
    });
    let expected: Vec<[f64; 3]> = vec![
        [0.0, 0.0, 0.0],
        [0.0, 0.5, 0.5],
        [0.5, 0.0, 0.5],
        [0.5, 0.5, 0.0],
    ];
    for (got, want) in actual.iter().zip(expected.iter()) {
        for k in 0..3 {
            assert!(
                (got[k] - want[k]).abs() < 1e-9,
                "coord mismatch: got {:?}, want {:?}",
                got,
                want
            );
        }
    }
}

#[test]
fn atom_set_equivalence_under_diagonal_supercell_on_diamond() {
    let s = Structure::diamond();
    let m = [[2, 0, 0], [0, 2, 0], [0, 0, 2]];
    let s2 = apply_supercell(&s, &m).unwrap();

    // Compare atom sets over a real-space cube strictly interior to the range
    // enumerated for each structure. `s2` has cells of side 2a; 5 cells of s2
    // span 10a, while 11 cells of s span 11a — both comfortably cover
    // [-3a, 3a]³.
    let size = DIAMOND_UNIT_CELL_SIZE_ANGSTROM;
    let aabb_min = DVec3::splat(-3.0 * size);
    let aabb_max = DVec3::splat(3.0 * size);

    let atoms_old = sort_atoms(enumerate_crystal_field_in_aabb(
        &s,
        IVec3::splat(-5),
        IVec3::splat(5),
        aabb_min,
        aabb_max,
    ));
    let atoms_new = sort_atoms(enumerate_crystal_field_in_aabb(
        &s2,
        IVec3::splat(-3),
        IVec3::splat(3),
        aabb_min,
        aabb_max,
    ));

    // Diamond has 8 sites per unit cell; the cube contains 6³ = 216 cells, so
    // 216 × 8 = 1728 atoms. Interior boundary clipping can remove some on the
    // +x/+y/+z faces (site positions ≥ 0 snap to ≥ 0 real coords). Main point:
    // the two enumerations should agree.
    assert!(!atoms_old.is_empty(), "expected non-empty atom set");
    assert_atom_sets_equal(&atoms_old, &atoms_new, 1e-8);
}

#[test]
fn bond_edge_set_equivalence_under_diagonal_supercell_on_diamond() {
    let s = Structure::diamond();
    let m = [[2, 0, 0], [0, 2, 0], [0, 0, 2]];
    let s2 = apply_supercell(&s, &m).unwrap();

    let size = DIAMOND_UNIT_CELL_SIZE_ANGSTROM;
    let aabb_min = DVec3::splat(-2.0 * size);
    let aabb_max = DVec3::splat(2.0 * size);

    let bonds_old = sort_bonds(enumerate_bonds_in_aabb(
        &s,
        IVec3::splat(-4),
        IVec3::splat(4),
        aabb_min,
        aabb_max,
    ));
    let bonds_new = sort_bonds(enumerate_bonds_in_aabb(
        &s2,
        IVec3::splat(-3),
        IVec3::splat(3),
        aabb_min,
        aabb_max,
    ));

    assert!(!bonds_old.is_empty(), "expected non-empty bond set");
    assert_bond_sets_equal(&bonds_old, &bonds_new, 1e-8);
}

#[test]
fn non_diagonal_rebasing_with_det_one_preserves_crystal_field() {
    let s = Structure::diamond();
    // Shear: det = 1. Equivalent-lattice rebasing, same volume.
    let m = [[1, 1, 0], [0, 1, 0], [0, 0, 1]];
    let s2 = apply_supercell(&s, &m).unwrap();

    assert_eq!(s2.motif.sites.len(), s.motif.sites.len());
    assert_eq!(s2.motif.bonds.len(), s.motif.bonds.len());

    let size = DIAMOND_UNIT_CELL_SIZE_ANGSTROM;
    let aabb_min = DVec3::splat(-2.0 * size);
    let aabb_max = DVec3::splat(2.0 * size);

    let atoms_old = sort_atoms(enumerate_crystal_field_in_aabb(
        &s,
        IVec3::splat(-4),
        IVec3::splat(4),
        aabb_min,
        aabb_max,
    ));
    let atoms_new = sort_atoms(enumerate_crystal_field_in_aabb(
        &s2,
        IVec3::splat(-4),
        IVec3::splat(4),
        aabb_min,
        aabb_max,
    ));

    assert_atom_sets_equal(&atoms_old, &atoms_new, 1e-8);
}

#[test]
fn double_supercell_equals_composition() {
    let s = Structure::diamond();
    let a = [[2, 0, 0], [0, 1, 0], [0, 0, 1]];
    let b = [[1, 0, 0], [0, 2, 0], [0, 0, 1]];
    // B · A as integer 3×3 (rows convention for M; composed by matrix product).
    let ba = [[2, 0, 0], [0, 2, 0], [0, 0, 1]];

    let step1 = apply_supercell(&s, &a).unwrap();
    let nested = apply_supercell(&step1, &b).unwrap();
    let composed = apply_supercell(&s, &ba).unwrap();

    assert_eq!(nested.motif.sites.len(), composed.motif.sites.len());
    assert_eq!(nested.motif.bonds.len(), composed.motif.bonds.len());

    // Compare crystal fields (bases differ trivially, but real-space atom sets
    // must match).
    let size = DIAMOND_UNIT_CELL_SIZE_ANGSTROM;
    let aabb_min = DVec3::splat(-2.0 * size);
    let aabb_max = DVec3::splat(2.0 * size);
    let atoms_nested = sort_atoms(enumerate_crystal_field_in_aabb(
        &nested,
        IVec3::splat(-3),
        IVec3::splat(3),
        aabb_min,
        aabb_max,
    ));
    let atoms_composed = sort_atoms(enumerate_crystal_field_in_aabb(
        &composed,
        IVec3::splat(-3),
        IVec3::splat(3),
        aabb_min,
        aabb_max,
    ));
    assert_atom_sets_equal(&atoms_nested, &atoms_composed, 1e-8);
}

#[test]
fn non_zero_motif_offset_transforms_under_minv_t() {
    let mut s = simple_cubic_carbon(3.0);
    s.motif_offset = DVec3::new(0.1, 0.2, 0.3);
    let m = [[2, 0, 0], [0, 2, 0], [0, 0, 2]];
    let s2 = apply_supercell(&s, &m).unwrap();

    // For diagonal (2,2,2), M⁻ᵀ is diag(0.5, 0.5, 0.5).
    let expected = DVec3::new(0.05, 0.10, 0.15);
    assert!(
        (s2.motif_offset - expected).length() < 1e-12,
        "expected {:?}, got {:?}",
        expected,
        s2.motif_offset
    );
}

#[test]
fn non_zero_motif_offset_preserves_crystal_field() {
    let mut s = Structure::diamond();
    s.motif_offset = DVec3::new(0.1, 0.2, 0.3);
    let m = [[2, 0, 0], [0, 2, 0], [0, 0, 2]];
    let s2 = apply_supercell(&s, &m).unwrap();

    let size = DIAMOND_UNIT_CELL_SIZE_ANGSTROM;
    let aabb_min = DVec3::splat(-2.0 * size);
    let aabb_max = DVec3::splat(2.0 * size);
    let atoms_old = sort_atoms(enumerate_crystal_field_in_aabb(
        &s,
        IVec3::splat(-4),
        IVec3::splat(4),
        aabb_min,
        aabb_max,
    ));
    let atoms_new = sort_atoms(enumerate_crystal_field_in_aabb(
        &s2,
        IVec3::splat(-3),
        IVec3::splat(3),
        aabb_min,
        aabb_max,
    ));
    assert_atom_sets_equal(&atoms_old, &atoms_new, 1e-8);
}

// --------------------------- Validation errors -----------------------------

#[test]
fn singular_matrix_returns_degenerate() {
    let s = Structure::diamond();
    let m = [[1, 0, 0], [2, 0, 0], [0, 0, 1]]; // rows 0 and 1 are linearly dependent
    let err = apply_supercell(&s, &m).unwrap_err();
    assert_eq!(err, SupercellError::Degenerate);
}

#[test]
fn diagonal_with_zero_component_returns_degenerate() {
    let s = Structure::diamond();
    let m = [[2, 0, 0], [0, 0, 0], [0, 0, 2]]; // det = 0
    let err = apply_supercell(&s, &m).unwrap_err();
    assert_eq!(err, SupercellError::Degenerate);
}

#[test]
fn negative_determinant_returns_inverted_handedness() {
    let s = Structure::diamond();
    // Swapping two rows flips the sign of det → det = -1.
    let m = [[0, 1, 0], [1, 0, 0], [0, 0, 1]];
    match apply_supercell(&s, &m).unwrap_err() {
        SupercellError::InvertedHandedness { det } => {
            assert_eq!(det, -1);
        }
        other => panic!("expected InvertedHandedness, got {:?}", other),
    }
}

#[test]
fn oversized_supercell_returns_too_large() {
    let s = Structure::diamond(); // 8 sites
    // det = 1_000_000, site count would be 8_000_000 ≫ 10_000.
    let m = [[100, 0, 0], [0, 100, 0], [0, 0, 100]];
    match apply_supercell(&s, &m).unwrap_err() {
        SupercellError::TooLarge { site_count, limit } => {
            assert_eq!(site_count, 8_000_000);
            assert_eq!(limit, MAX_SUPERCELL_SITES);
        }
        other => panic!("expected TooLarge, got {:?}", other),
    }
}
