// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'common_api_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `generate_mock_image`, `initialize_cad_instance_async`, `send_texture`, `to_api_camera_canonical_view`, `to_renderer_camera_canonical_view`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `RGBA_FUNCTION`, `TEXTURE_RGBA_RENDERER_PLUGIN`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `deref`, `deref`, `initialize`, `initialize`

/// Set the viewport size for rendering
void setViewportSize({required int width, required int height}) =>
    RustLib.instance.api
        .crateApiCommonApiSetViewportSize(width: width, height: height);

double provideTexture({required int texturePtr}) => RustLib.instance.api
    .crateApiCommonApiProvideTexture(texturePtr: texturePtr);

APICamera? getCamera() => RustLib.instance.api.crateApiCommonApiGetCamera();

void moveCamera(
        {required APIVec3 eye, required APIVec3 target, required APIVec3 up}) =>
    RustLib.instance.api
        .crateApiCommonApiMoveCamera(eye: eye, target: target, up: up);

int? gadgetHitTest(
        {required APIVec3 rayOrigin, required APIVec3 rayDirection}) =>
    RustLib.instance.api.crateApiCommonApiGadgetHitTest(
        rayOrigin: rayOrigin, rayDirection: rayDirection);

void gadgetStartDrag(
        {required int handleIndex,
        required APIVec3 rayOrigin,
        required APIVec3 rayDirection}) =>
    RustLib.instance.api.crateApiCommonApiGadgetStartDrag(
        handleIndex: handleIndex,
        rayOrigin: rayOrigin,
        rayDirection: rayDirection);

void gadgetDrag(
        {required int handleIndex,
        required APIVec3 rayOrigin,
        required APIVec3 rayDirection}) =>
    RustLib.instance.api.crateApiCommonApiGadgetDrag(
        handleIndex: handleIndex,
        rayOrigin: rayOrigin,
        rayDirection: rayDirection);

void gadgetEndDrag() => RustLib.instance.api.crateApiCommonApiGadgetEndDrag();

bool syncGadgetData() => RustLib.instance.api.crateApiCommonApiSyncGadgetData();

APITransform getCameraTransform() =>
    RustLib.instance.api.crateApiCommonApiGetCameraTransform();

/// Adjusts the pivot point of the camera based on a raycast into the scene
///
/// This function performs the following steps:
/// 1. Traces a ray into the scene based on the active editor
/// 2. If the ray hits something that point will be the new pivot point
///
/// # Arguments
///
/// * `ray_origin` - The origin point of the ray in world space
/// * `ray_direction` - The direction vector of the ray (does not need to be normalized)
void adjustCameraTarget(
        {required APIVec3 rayOrigin, required APIVec3 rayDirection}) =>
    RustLib.instance.api.crateApiCommonApiAdjustCameraTarget(
        rayOrigin: rayOrigin, rayDirection: rayDirection);

void setCameraTransform({required APITransform transform}) =>
    RustLib.instance.api
        .crateApiCommonApiSetCameraTransform(transform: transform);

/// Set the camera to use orthographic or perspective projection
void setOrthographicMode({required bool orthographic}) => RustLib.instance.api
    .crateApiCommonApiSetOrthographicMode(orthographic: orthographic);

/// Get whether the camera is using orthographic projection
bool isOrthographic() => RustLib.instance.api.crateApiCommonApiIsOrthographic();

/// Set the orthographic half height (controls zoom level in orthographic mode)
void setOrthoHalfHeight({required double halfHeight}) => RustLib.instance.api
    .crateApiCommonApiSetOrthoHalfHeight(halfHeight: halfHeight);

/// Get the current orthographic half height
double getOrthoHalfHeight() =>
    RustLib.instance.api.crateApiCommonApiGetOrthoHalfHeight();

/// Get the canonical view of the current camera orientation
/// Returns one of: Custom, Top, Bottom, Front, Back, Left, Right
APICameraCanonicalView getCameraCanonicalView() =>
    RustLib.instance.api.crateApiCommonApiGetCameraCanonicalView();

/// Set the camera to a canonical view orientation
/// Accepts one of: Custom, Top, Bottom, Front, Back, Left, Right
/// If Custom is provided, no changes will be made to the camera orientation
void setCameraCanonicalView({required APICameraCanonicalView view}) =>
    RustLib.instance.api.crateApiCommonApiSetCameraCanonicalView(view: view);

String greet({required String name}) =>
    RustLib.instance.api.crateApiCommonApiGreet(name: name);

/// Returns a list of all chemical elements with their atomic numbers and names,
/// ordered by atomic number
List<ElementSummary> getAllElements() =>
    RustLib.instance.api.crateApiCommonApiGetAllElements();
