// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'common_api_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

enum APISceneComposerTool {
  default_,
  align,
  atomInfo,
  distance,
  ;
}

class AtomView {
  final BigInt id;
  final int atomicNumber;
  final String symbol;
  final BigInt clusterId;
  final String clusterName;
  final APIVec3 position;
  final String elementName;
  final double covalentRadius;

  const AtomView({
    required this.id,
    required this.atomicNumber,
    required this.symbol,
    required this.clusterId,
    required this.clusterName,
    required this.position,
    required this.elementName,
    required this.covalentRadius,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      atomicNumber.hashCode ^
      symbol.hashCode ^
      clusterId.hashCode ^
      clusterName.hashCode ^
      position.hashCode ^
      elementName.hashCode ^
      covalentRadius.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AtomView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          atomicNumber == other.atomicNumber &&
          symbol == other.symbol &&
          clusterId == other.clusterId &&
          clusterName == other.clusterName &&
          position == other.position &&
          elementName == other.elementName &&
          covalentRadius == other.covalentRadius;
}

class ClusterView {
  final BigInt id;
  final String name;
  final bool selected;

  const ClusterView({
    required this.id,
    required this.name,
    required this.selected,
  });

  @override
  int get hashCode => id.hashCode ^ name.hashCode ^ selected.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClusterView &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          name == other.name &&
          selected == other.selected;
}

class SceneComposerView {
  final List<ClusterView> clusters;
  final APISceneComposerTool activeTool;
  final List<APISceneComposerTool> availableTools;
  final bool isUndoAvailable;
  final bool isRedoAvailable;

  const SceneComposerView({
    required this.clusters,
    required this.activeTool,
    required this.availableTools,
    required this.isUndoAvailable,
    required this.isRedoAvailable,
  });

  @override
  int get hashCode =>
      clusters.hashCode ^
      activeTool.hashCode ^
      availableTools.hashCode ^
      isUndoAvailable.hashCode ^
      isRedoAvailable.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SceneComposerView &&
          runtimeType == other.runtimeType &&
          clusters == other.clusters &&
          activeTool == other.activeTool &&
          availableTools == other.availableTools &&
          isUndoAvailable == other.isUndoAvailable &&
          isRedoAvailable == other.isRedoAvailable;
}
