// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../common_api_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `build`, `record_to_json`, `record_to_markdown`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// Bumped on every push, on `clear`, and on a session-label change.
///
/// The refresh gate of D12: without it `refreshFromKernel` has no cheap way to
/// know the list is unchanged, and would marshal every summary on every tick.
BigInt aiHistoryVersion() => RustLib.instance.api
    .crateApiStructureDesignerAiHistoryApiAiHistoryVersion();

/// Every retained entry as a lightweight row, oldest first.
List<APIAiEditSummary> aiHistoryList() =>
    RustLib.instance.api.crateApiStructureDesignerAiHistoryApiAiHistoryList();

/// One entry in full, or `None` when it has been evicted by the ring's caps.
APIAiEditDetail? aiHistoryDetail({required BigInt seq}) => RustLib.instance.api
    .crateApiStructureDesignerAiHistoryApiAiHistoryDetail(seq: seq);

/// One entry's diff, computed on demand (D5).
///
/// `by_node` selects the default *By node* view — the set difference over
/// per-node blocks, stable against the reordering a topological sort produces
/// — over the literal unified *Text* diff.
APIAiDiff? aiHistoryDiff({required BigInt seq, required bool byNode}) =>
    RustLib.instance.api.crateApiStructureDesignerAiHistoryApiAiHistoryDiff(
        seq: seq, byNode: byNode);

/// The whole session as JSON — the canonical export form, machine-comparable
/// across sessions and models (D10). The caller writes it through the standard
/// file-save path so it picks up the last-directory behaviour.
String aiHistoryExportJson() => RustLib.instance.api
    .crateApiStructureDesignerAiHistoryApiAiHistoryExportJson();

/// The whole session as Markdown — a convenience for pasting into a
/// skill-refinement conversation, where JSON would be unreadable.
String aiHistoryExportMarkdown() => RustLib.instance.api
    .crateApiStructureDesignerAiHistoryApiAiHistoryExportMarkdown();

/// Drop every entry. `seq` keeps counting, so an exported log stays
/// unambiguous.
void aiHistoryClear() =>
    RustLib.instance.api.crateApiStructureDesignerAiHistoryApiAiHistoryClear();

/// Set the free-text session label (D13) — "Opus 5 / skill v3". The application
/// cannot know which model is driving the CLI, so it is asked; the label is
/// stamped into exports.
void aiHistorySetSessionLabel({required String label}) => RustLib.instance.api
    .crateApiStructureDesignerAiHistoryApiAiHistorySetSessionLabel(
        label: label);

String aiHistoryGetSessionLabel() => RustLib.instance.api
    .crateApiStructureDesignerAiHistoryApiAiHistoryGetSessionLabel();

/// One entry's computed diff.
class APIAiDiff {
  final bool byNode;

  /// Only the blocks that differ. Empty means the two snapshots are
  /// equivalent — which is exactly what a `--replace` of an unchanged script
  /// produces, because identities and positions survive one.
  final List<APIDiffHunk> hunks;

  /// How many blocks were identical and so were collapsed away.
  final int unchangedCount;

  /// Both snapshots are faithful. When false the panel banners the entry and
  /// greys the diff: a truncated `after_text` would otherwise fill the
  /// *removed* column with nodes that still exist (D2).
  final bool snapshotsComplete;

  const APIAiDiff({
    required this.byNode,
    required this.hunks,
    required this.unchangedCount,
    required this.snapshotsComplete,
  });

  @override
  int get hashCode =>
      byNode.hashCode ^
      hunks.hashCode ^
      unchangedCount.hashCode ^
      snapshotsComplete.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIAiDiff &&
          runtimeType == other.runtimeType &&
          byNode == other.byNode &&
          hunks == other.hunks &&
          unchangedCount == other.unchangedCount &&
          snapshotsComplete == other.snapshotsComplete;
}

/// One entry in full: the submitted script, the whole `EditResult`, both
/// snapshots and the layout outcome. Fetched for the selected row only.
class APIAiEditDetail {
  final BigInt seq;
  final PlatformInt64 timestampMs;
  final String networkName;
  final bool replace;

  /// Exactly what the AI submitted.
  final String code;
  final bool applied;
  final bool success;

  /// Node **paths** (`m1/a`), the same key the diff uses.
  final List<String> nodesCreated;
  final List<String> nodesUpdated;
  final List<String> nodesDeleted;
  final List<String> connectionsMade;

  /// The three `EditResult` fields it is easy to drop on the floor.
  /// `output_set` is how "the AI re-pointed the network's return node" is
  /// visible at all (D8).
  final String? descriptionSet;
  final String? summarySet;
  final String? outputSet;
  final List<String> errors;
  final List<String> warnings;

  /// AI text-format snapshots (D2), **not** `.cnnd`. Empty on the rejection
  /// paths, which never reached the network.
  final String beforeText;
  final String afterText;
  final bool beforeComplete;
  final bool afterComplete;
  final bool diverged;
  final bool divergedByUndo;
  final APILayoutOutcome layout;

  const APIAiEditDetail({
    required this.seq,
    required this.timestampMs,
    required this.networkName,
    required this.replace,
    required this.code,
    required this.applied,
    required this.success,
    required this.nodesCreated,
    required this.nodesUpdated,
    required this.nodesDeleted,
    required this.connectionsMade,
    this.descriptionSet,
    this.summarySet,
    this.outputSet,
    required this.errors,
    required this.warnings,
    required this.beforeText,
    required this.afterText,
    required this.beforeComplete,
    required this.afterComplete,
    required this.diverged,
    required this.divergedByUndo,
    required this.layout,
  });

  @override
  int get hashCode =>
      seq.hashCode ^
      timestampMs.hashCode ^
      networkName.hashCode ^
      replace.hashCode ^
      code.hashCode ^
      applied.hashCode ^
      success.hashCode ^
      nodesCreated.hashCode ^
      nodesUpdated.hashCode ^
      nodesDeleted.hashCode ^
      connectionsMade.hashCode ^
      descriptionSet.hashCode ^
      summarySet.hashCode ^
      outputSet.hashCode ^
      errors.hashCode ^
      warnings.hashCode ^
      beforeText.hashCode ^
      afterText.hashCode ^
      beforeComplete.hashCode ^
      afterComplete.hashCode ^
      diverged.hashCode ^
      divergedByUndo.hashCode ^
      layout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIAiEditDetail &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          timestampMs == other.timestampMs &&
          networkName == other.networkName &&
          replace == other.replace &&
          code == other.code &&
          applied == other.applied &&
          success == other.success &&
          nodesCreated == other.nodesCreated &&
          nodesUpdated == other.nodesUpdated &&
          nodesDeleted == other.nodesDeleted &&
          connectionsMade == other.connectionsMade &&
          descriptionSet == other.descriptionSet &&
          summarySet == other.summarySet &&
          outputSet == other.outputSet &&
          errors == other.errors &&
          warnings == other.warnings &&
          beforeText == other.beforeText &&
          afterText == other.afterText &&
          beforeComplete == other.beforeComplete &&
          afterComplete == other.afterComplete &&
          diverged == other.diverged &&
          divergedByUndo == other.divergedByUndo &&
          layout == other.layout;
}

/// One list row: what the panel's master pane needs and nothing more (D12).
class APIAiEditSummary {
  final BigInt seq;
  final PlatformInt64 timestampMs;

  /// May be empty on the "no active network" rejection path.
  final String networkName;

  /// `--replace` was used. The row badges this unmissably: it is the
  /// difference between a merge and a whole-network rebuild.
  final bool replace;

  /// The editor's own verdict — the statements parsed and landed. This is the
  /// row's primary glyph, and the one that answers "did this edit work".
  final bool applied;

  /// The network validates afterwards. A *whole-network* verdict, so
  /// `applied && !success` is ordinary rather than exceptional: creating an
  /// HOF node before filling its body produces it every time (D8).
  final bool success;
  final int createdCount;
  final int updatedCount;
  final int deletedCount;
  final int errorCount;
  final int warningCount;

  /// The network changed between this edit and the previous one for the same
  /// network (D7).
  final bool diverged;

  /// …and the gap is explained by an undo or redo of an AI edit, so the
  /// marker reads "edit #N undone" rather than the general wording.
  final bool divergedByUndo;

  /// Both snapshots are faithful. False means the serializer aborted on a
  /// wire cycle, so the diff is untrustworthy and the text is not valid
  /// `edit --replace` input (D2).
  final bool snapshotsComplete;
  final int movedCount;

  const APIAiEditSummary({
    required this.seq,
    required this.timestampMs,
    required this.networkName,
    required this.replace,
    required this.applied,
    required this.success,
    required this.createdCount,
    required this.updatedCount,
    required this.deletedCount,
    required this.errorCount,
    required this.warningCount,
    required this.diverged,
    required this.divergedByUndo,
    required this.snapshotsComplete,
    required this.movedCount,
  });

  @override
  int get hashCode =>
      seq.hashCode ^
      timestampMs.hashCode ^
      networkName.hashCode ^
      replace.hashCode ^
      applied.hashCode ^
      success.hashCode ^
      createdCount.hashCode ^
      updatedCount.hashCode ^
      deletedCount.hashCode ^
      errorCount.hashCode ^
      warningCount.hashCode ^
      diverged.hashCode ^
      divergedByUndo.hashCode ^
      snapshotsComplete.hashCode ^
      movedCount.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIAiEditSummary &&
          runtimeType == other.runtimeType &&
          seq == other.seq &&
          timestampMs == other.timestampMs &&
          networkName == other.networkName &&
          replace == other.replace &&
          applied == other.applied &&
          success == other.success &&
          createdCount == other.createdCount &&
          updatedCount == other.updatedCount &&
          deletedCount == other.deletedCount &&
          errorCount == other.errorCount &&
          warningCount == other.warningCount &&
          diverged == other.diverged &&
          divergedByUndo == other.divergedByUndo &&
          snapshotsComplete == other.snapshotsComplete &&
          movedCount == other.movedCount;
}

/// Flutter-facing mirror of [`DeltaCounts`]. `None` on the record until
/// `doc/design_incremental_layout.md` Phase 1 lands.
class APIDeltaCounts {
  final int nodesAdded;
  final int nodesModified;
  final int nodesRemoved;
  final int wiresAdded;
  final int wiresRemoved;

  const APIDeltaCounts({
    required this.nodesAdded,
    required this.nodesModified,
    required this.nodesRemoved,
    required this.wiresAdded,
    required this.wiresRemoved,
  });

  @override
  int get hashCode =>
      nodesAdded.hashCode ^
      nodesModified.hashCode ^
      nodesRemoved.hashCode ^
      wiresAdded.hashCode ^
      wiresRemoved.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIDeltaCounts &&
          runtimeType == other.runtimeType &&
          nodesAdded == other.nodesAdded &&
          nodesModified == other.nodesModified &&
          nodesRemoved == other.nodesRemoved &&
          wiresAdded == other.wiresAdded &&
          wiresRemoved == other.wiresRemoved;
}

/// One block's worth of difference.
class APIDiffHunk {
  final APIDiffHunkKind kind;

  /// *By node*: the scoped path (`m1/d`), the same key `EditResult` uses, so
  /// the *Diff* and *Result* tabs name a node identically. Empty for the root
  /// scope's header / `description` / `summary` / `output` bucket.
  /// *Text*: the unified diff's `@@ … @@` range header.
  final String nodePath;
  final List<APIDiffLine> lines;

  const APIDiffHunk({
    required this.kind,
    required this.nodePath,
    required this.lines,
  });

  @override
  int get hashCode => kind.hashCode ^ nodePath.hashCode ^ lines.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIDiffHunk &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          nodePath == other.nodePath &&
          lines == other.lines;
}

/// Flutter-facing mirror of [`DiffHunkKind`].
enum APIDiffHunkKind {
  added,
  removed,
  changed,
  ;
}

/// One rendered diff line. Rendered, not re-parsed, by Dart.
class APIDiffLine {
  final APIDiffLineTag tag;
  final String text;

  const APIDiffLine({
    required this.tag,
    required this.text,
  });

  @override
  int get hashCode => tag.hashCode ^ text.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIDiffLine &&
          runtimeType == other.runtimeType &&
          tag == other.tag &&
          text == other.text;
}

/// Flutter-facing mirror of [`DiffLineTag`].
enum APIDiffLineTag {
  same,
  add,
  remove,
  ;
}

/// Flutter-facing mirror of [`LayoutOutcome`]: what layout did to the drawing.
///
/// `path` describes what the layout pass did to the **root scope** only, so
/// `APILayoutPath::None` with a non-empty `moved` is correct and ordinary — a
/// body node is never reflowed but is still re-placed at creation time. The
/// panel must say which, rather than reading `None` as "nothing was disturbed"
/// (D9).
class APILayoutOutcome {
  final APILayoutPath path;

  /// Every node in the network, bodies included.
  final int nodeCount;
  final List<APIMovedNode> moved;
  final double maxDisplacement;
  final APIDeltaCounts? delta;

  const APILayoutOutcome({
    required this.path,
    required this.nodeCount,
    required this.moved,
    required this.maxDisplacement,
    this.delta,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      nodeCount.hashCode ^
      moved.hashCode ^
      maxDisplacement.hashCode ^
      delta.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APILayoutOutcome &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          nodeCount == other.nodeCount &&
          moved == other.moved &&
          maxDisplacement == other.maxDisplacement &&
          delta == other.delta;
}

/// Flutter-facing mirror of [`LayoutPath`]: which layout algorithm ran over the
/// **root scope** after the edit.
enum APILayoutPath {
  none,
  fullReflow,
  incremental,
  ;
}

/// Flutter-facing mirror of [`MovedNode`].
class APIMovedNode {
  /// The scoped node path, rendered `m1/d`. Never a bare name: body names are
  /// unique per scope only, so `m1/d` and `m2/d` are different nodes (D9).
  final String path;

  /// How many scopes deep the node sits — `0` for the root scope. The panel's
  /// Layout tab groups by this, because a move inside a body comes from
  /// creation-time placement rather than from the layout pass.
  final int depth;
  final APIVec2 before;
  final APIVec2 after;
  final double displacement;

  const APIMovedNode({
    required this.path,
    required this.depth,
    required this.before,
    required this.after,
    required this.displacement,
  });

  @override
  int get hashCode =>
      path.hashCode ^
      depth.hashCode ^
      before.hashCode ^
      after.hashCode ^
      displacement.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIMovedNode &&
          runtimeType == other.runtimeType &&
          path == other.path &&
          depth == other.depth &&
          before == other.before &&
          after == other.after &&
          displacement == other.displacement;
}
