// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../common_api_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'structure_designer_api_types.dart';

// These functions are ignored because they are not marked as `pub`: `collect_frozen_base_atom_ids`, `gather_frozen_base_atoms_promotion_info`, `gather_selected_base_promotion_info_including_frozen`, `gather_selected_base_promotion_info`, `toggle_atom_edit_flag`

bool atomEditSelectByRay(
        {required APIVec3 rayStart,
        required APIVec3 rayDir,
        required SelectModifier selectModifier}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditSelectByRay(
            rayStart: rayStart, rayDir: rayDir, selectModifier: selectModifier);

void atomEditAddAtomByRay(
        {required int atomicNumber,
        required APIVec3 planeNormal,
        required APIVec3 rayStart,
        required APIVec3 rayDir,
        required APIHybridization hybridizationOverride}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditAddAtomByRay(
            atomicNumber: atomicNumber,
            planeNormal: planeNormal,
            rayStart: rayStart,
            rayDir: rayDir,
            hybridizationOverride: hybridizationOverride);

/// Add an atom at an exact position (typed in by the user).
void atomEditAddAtomAtPosition(
        {required int atomicNumber,
        required APIVec3 position,
        required APIHybridization hybridizationOverride}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditAddAtomAtPosition(
            atomicNumber: atomicNumber,
            position: position,
            hybridizationOverride: hybridizationOverride);

/// Pointer down in AddBond tool. Returns whether an atom was hit.
/// Triggers one refresh if an atom is hit (to show source atom highlight).
bool addBondPointerDown(
        {required APIVec2 screenPos,
        required APIVec3 rayOrigin,
        required APIVec3 rayDirection}) =>
    RustLib.instance.api.crateApiStructureDesignerAtomEditApiAddBondPointerDown(
        screenPos: screenPos, rayOrigin: rayOrigin, rayDirection: rayDirection);

/// Pointer move in AddBond tool. Returns preview state for rubber-band rendering.
/// NO refresh, NO evaluation — only a ray-cast hit test.
APIAddBondMoveResult addBondPointerMove(
        {required APIVec2 screenPos,
        required APIVec3 rayOrigin,
        required APIVec3 rayDirection}) =>
    RustLib.instance.api.crateApiStructureDesignerAtomEditApiAddBondPointerMove(
        screenPos: screenPos, rayOrigin: rayOrigin, rayDirection: rayDirection);

/// Pointer up in AddBond tool. Creates bond if released on valid target.
/// Triggers one refresh to show the new bond (or remove source highlight on cancel).
bool addBondPointerUp(
        {required APIVec3 rayOrigin, required APIVec3 rayDirection}) =>
    RustLib.instance.api.crateApiStructureDesignerAtomEditApiAddBondPointerUp(
        rayOrigin: rayOrigin, rayDirection: rayDirection);

/// Cancel AddBond tool interaction (reset to Idle).
void addBondPointerCancel() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAddBondPointerCancel();

/// Set the bond order for the AddBond tool (1-7).
void setAddBondOrder({required int order}) => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiSetAddBondOrder(order: order);

/// Change the order of all selected bonds (in Default tool).
void changeSelectedBondsOrder({required int newOrder}) => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiChangeSelectedBondsOrder(
        newOrder: newOrder);

void atomEditDeleteSelected() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditDeleteSelected();

void atomEditReplaceSelected({required int atomicNumber}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditReplaceSelected(
            atomicNumber: atomicNumber);

void atomEditTransformSelected({required APITransform absTransform}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditTransformSelected(
            absTransform: absTransform);

bool atomEditToggleShowAnchorArrows() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditToggleShowAnchorArrows();

bool atomEditToggleShowGadget() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditToggleShowGadget();

bool atomEditToggleIncludeBaseBondsInDiff() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditToggleIncludeBaseBondsInDiff();

bool atomEditToggleErrorOnStaleEntries() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditToggleErrorOnStaleEntries();

bool atomEditToggleContinuousMinimization() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditToggleContinuousMinimization();

bool atomEditSetTolerance({required double value}) => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditSetTolerance(value: value);

APIAtomEditTool? getActiveAtomEditTool() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiGetActiveAtomEditTool();

bool setActiveAtomEditTool({required APIAtomEditTool tool}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiSetActiveAtomEditTool(tool: tool);

void setAtomEditSelectedElement({required int atomicNumber}) => RustLib
    .instance.api
    .crateApiStructureDesignerAtomEditApiSetAtomEditSelectedElement(
        atomicNumber: atomicNumber);

/// Add a new parameter element to the active motif_edit node.
void motifEditAddParameterElement(
        {required String name, required int defaultAtomicNumber}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiMotifEditAddParameterElement(
            name: name, defaultAtomicNumber: defaultAtomicNumber);

/// Remove a parameter element by index from the active motif_edit node.
void motifEditRemoveParameterElement({required BigInt index}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiMotifEditRemoveParameterElement(
            index: index);

/// Update a parameter element's name and default at the given index.
void motifEditUpdateParameterElement(
        {required BigInt index,
        required String name,
        required int defaultAtomicNumber}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiMotifEditUpdateParameterElement(
            index: index, name: name, defaultAtomicNumber: defaultAtomicNumber);

double motifEditGetNeighborDepth() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiMotifEditGetNeighborDepth();

void motifEditSetNeighborDepth({required double value}) => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiMotifEditSetNeighborDepth(
        value: value);

String atomEditMinimize({required APIMinimizeFreezeMode freezeMode}) =>
    RustLib.instance.api.crateApiStructureDesignerAtomEditApiAtomEditMinimize(
        freezeMode: freezeMode);

String atomEditAddHydrogen({required bool selectedOnly}) => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditAddHydrogen(
        selectedOnly: selectedOnly);

String atomEditRemoveHydrogen({required bool selectedOnly}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditRemoveHydrogen(
            selectedOnly: selectedOnly);

GuidedPlacementApiResult atomEditStartGuidedPlacement(
        {required APIVec3 rayStart,
        required APIVec3 rayDir,
        required int atomicNumber,
        required APIHybridization hybridizationOverride,
        required APIBondMode bondMode,
        required APIBondLengthMode bondLengthMode}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditStartGuidedPlacement(
            rayStart: rayStart,
            rayDir: rayDir,
            atomicNumber: atomicNumber,
            hybridizationOverride: hybridizationOverride,
            bondMode: bondMode,
            bondLengthMode: bondLengthMode);

bool atomEditPlaceGuidedAtom(
        {required APIVec3 rayStart, required APIVec3 rayDir}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditPlaceGuidedAtom(
            rayStart: rayStart, rayDir: rayDir);

void atomEditCancelGuidedPlacement() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditCancelGuidedPlacement();

bool atomEditIsInGuidedPlacement() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditIsInGuidedPlacement();

/// Update the preview position for free sphere guided placement.
/// Returns true if the preview changed (needs re-render).
bool atomEditGuidedPlacementPointerMove(
        {required APIVec3 rayStart, required APIVec3 rayDir}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditGuidedPlacementPointerMove(
            rayStart: rayStart, rayDir: rayDir);

void defaultToolPointerCancel() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiDefaultToolPointerCancel();

PointerDownResult defaultToolPointerDown(
        {required APIVec2 screenPos,
        required APIVec3 rayOrigin,
        required APIVec3 rayDirection,
        required SelectModifier selectModifier}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiDefaultToolPointerDown(
            screenPos: screenPos,
            rayOrigin: rayOrigin,
            rayDirection: rayDirection,
            selectModifier: selectModifier);

PointerMoveResult defaultToolPointerMove(
        {required APIVec2 screenPos,
        required APIVec3 rayOrigin,
        required APIVec3 rayDirection,
        required double viewportWidth,
        required double viewportHeight}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiDefaultToolPointerMove(
            screenPos: screenPos,
            rayOrigin: rayOrigin,
            rayDirection: rayDirection,
            viewportWidth: viewportWidth,
            viewportHeight: viewportHeight);

PointerUpResult defaultToolPointerUp(
        {required APIVec2 screenPos,
        required APIVec3 rayOrigin,
        required APIVec3 rayDirection,
        required SelectModifier selectModifier,
        required double viewportWidth,
        required double viewportHeight}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiDefaultToolPointerUp(
            screenPos: screenPos,
            rayOrigin: rayOrigin,
            rayDirection: rayDirection,
            selectModifier: selectModifier,
            viewportWidth: viewportWidth,
            viewportHeight: viewportHeight);

/// Modify the distance between two selected atoms.
/// `move_first`: true = move atom1, false = move atom2.
/// Returns an error message string on failure, empty string on success.
String atomEditModifyDistance(
        {required double targetDistance,
        required bool moveFirst,
        required bool moveFragment}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditModifyDistance(
            targetDistance: targetDistance,
            moveFirst: moveFirst,
            moveFragment: moveFragment);

/// Modify the angle at the vertex of three selected atoms.
/// `move_arm_a`: true = move arm A, false = move arm B.
/// Returns an error message string on failure, empty string on success.
String atomEditModifyAngle(
        {required double targetAngleDegrees,
        required bool moveArmA,
        required bool moveFragment}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditModifyAngle(
            targetAngleDegrees: targetAngleDegrees,
            moveArmA: moveArmA,
            moveFragment: moveFragment);

/// Modify the dihedral angle of four selected atoms.
/// `move_a_side`: true = rotate A-side, false = rotate D-side.
/// Returns an error message string on failure, empty string on success.
String atomEditModifyDihedral(
        {required double targetAngleDegrees,
        required bool moveASide,
        required bool moveFragment}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditModifyDihedral(
            targetAngleDegrees: targetAngleDegrees,
            moveASide: moveASide,
            moveFragment: moveFragment);

/// Mark a result-space atom for highlighting while the modify measurement dialog is open.
/// Triggers a refresh to render the yellow crosshair.
void atomEditSetMeasurementMark({required int resultAtomId}) => RustLib
    .instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditSetMeasurementMark(
        resultAtomId: resultAtomId);

/// Clear the measurement mark (when the dialog closes).
/// Triggers a refresh to remove the crosshair.
void atomEditClearMeasurementMark() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditClearMeasurementMark();

/// Get the default (equilibrium) bond length for the two selected atoms.
/// Returns None if atoms are not bonded or if UFF typing fails.
double? atomEditGetDefaultBondLength(
        {required APIBondLengthMode bondLengthMode}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditGetDefaultBondLength(
            bondLengthMode: bondLengthMode);

/// Get the default (equilibrium) angle for the three selected atoms.
/// Returns None if UFF typing fails for the vertex atom.
double? atomEditGetDefaultAngle() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditGetDefaultAngle();

/// Sets the frozen flag on all currently selected atoms (additive).
/// Base atoms are promoted to diff first.
void atomEditSelectionToFrozen() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditSelectionToFrozen();

/// Clears the frozen flag on all currently selected atoms.
/// Base atoms (e.g., frozen atoms from upstream nodes) are promoted to diff first.
void atomEditSelectionToUnfrozen() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditSelectionToUnfrozen();

/// Replaces the current selection with the set of frozen atoms (diff and base).
void atomEditFrozenToSelection() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditFrozenToSelection();

/// Clears the frozen flag from all atoms (diff and frozen base atoms from upstream).
void atomEditClearFrozen() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditClearFrozen();

/// Returns true if any atom (diff or base from upstream) has the frozen flag set.
bool atomEditHasFrozenAtoms() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditHasFrozenAtoms();

/// Sets the hybridization override on all currently selected atoms.
/// `Auto` removes the override (restoring bond-based inference).
/// Base atoms are promoted to diff first.
void atomEditSetHybridizationOverride(
        {required APIHybridization hybridization}) =>
    RustLib.instance.api
        .crateApiStructureDesignerAtomEditApiAtomEditSetHybridizationOverride(
            hybridization: hybridization);

/// Returns the common hybridization override of the currently selected atoms.
/// Returns -1 if no atom_edit is active or no atoms are selected.
/// Returns 0 (Auto), 1 (Sp3), 2 (Sp2), or 3 (Sp1) if all selected atoms agree.
/// Returns -2 if selected atoms have differing overrides (mixed state).
int atomEditGetSelectedHybridization() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditGetSelectedHybridization();

/// Returns the common *inferred* hybridization of the currently selected atoms.
///
/// This always returns the bond-order-based inference (ignoring overrides), so the
/// UI can show "Auto (sp3)" etc. when the override is Auto.
///
/// Returns -1 if no atom_edit is active, no atoms are selected, or the result
/// structure is unavailable.
/// Returns 1 (Sp3), 2 (Sp2), or 3 (Sp1) if all selected atoms agree.
/// Returns -2 if selected atoms have differing inferred hybridizations (mixed).
int atomEditGetSelectedInferredHybridization() => RustLib.instance.api
    .crateApiStructureDesignerAtomEditApiAtomEditGetSelectedInferredHybridization();
