// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'structure_designer_api_types.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `chemisorb_node_data`, `chemisorb_node_report`, `format_run_result`, `resolve_node_identifier`, `set_chemisorb_node_data`

APIChemisorbData? getChemisorbData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api.crateApiStructureDesignerChemisorbApiGetChemisorbData(
        scopePath: scopePath, nodeId: nodeId);

void setChemisorbData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIChemisorbData data}) =>
    RustLib.instance.api.crateApiStructureDesignerChemisorbApiSetChemisorbData(
        scopePath: scopePath, nodeId: nodeId, data: data);

APIChemisorbReport? getChemisorbReport() => RustLib.instance.api
    .crateApiStructureDesignerChemisorbApiGetChemisorbReport();

/// **Run**: searches with the node and stores the result, then refreshes so
/// the outputs show it. Synchronous — seconds to minutes; the panel shows a
/// modal placard meanwhile. `Err` carries a message for the user.
APIChemisorbRunResult runChemisorb(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api.crateApiStructureDesignerChemisorbApiRunChemisorb(
        scopePath: scopePath, nodeId: nodeId);

/// **Run** by node name or id in the active network, for the CLI's `run`
/// command. Returns the summary as text.
String runChemisorbNode({required String nodeIdentifier}) =>
    RustLib.instance.api.crateApiStructureDesignerChemisorbApiRunChemisorbNode(
        nodeIdentifier: nodeIdentifier);
