// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'structure_designer_api_types.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `chemisorb_node_data`, `chemisorb_node_report`, `set_chemisorb_node_data`

APIChemisorbData? getChemisorbData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api.crateApiStructureDesignerChemisorbApiGetChemisorbData(
        scopePath: scopePath, nodeId: nodeId);

void setChemisorbData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIChemisorbData data}) =>
    RustLib.instance.api.crateApiStructureDesignerChemisorbApiSetChemisorbData(
        scopePath: scopePath, nodeId: nodeId, data: data);

APIChemisorbReport? getChemisorbReport() => RustLib.instance.api
    .crateApiStructureDesignerChemisorbApiGetChemisorbReport();
