// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../common_api_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'structure_designer_api_types.dart';

// These functions are ignored because they are not marked as `pub`: `no_instance`, `show_active`, `store_outgoing_camera`

/// The open documents in tab order.
List<APIDocumentTab> listDocuments() =>
    RustLib.instance.api.crateApiStructureDesignerDocumentsApiListDocuments();

/// *File > New*: a fresh Untitled tab after the active one, activated. Set up
/// as `new_project_direct_editing` when `direct_editing`, else as
/// `new_project`. Refused during an open interaction (D4).
APIResult newDocument({required bool directEditing}) =>
    RustLib.instance.api.crateApiStructureDesignerDocumentsApiNewDocument(
        directEditing: directEditing);

/// *File > Open*: activates the tab that has `file_path` open (D5), or loads
/// the file into a new tab — replacing a pristine active Untitled tab. A failed
/// load adds no tab and leaves the active document untouched.
APIOpenDocumentResult openDocument({required String filePath}) =>
    RustLib.instance.api
        .crateApiStructureDesignerDocumentsApiOpenDocument(filePath: filePath);

/// Makes document `id` the active one (the swap of §5.2). Refused during an
/// open interaction (D4) or for an unknown id.
APIActivateResult activateDocument({required BigInt id}) => RustLib.instance.api
    .crateApiStructureDesignerDocumentsApiActivateDocument(id: id);

/// Closes document `id` — no dirty check, Flutter asks first. Closing the
/// active tab activates its neighbour first (refused during an open
/// interaction, D4); closing the last tab leaves a fresh Untitled one.
APIActivateResult closeDocument({required BigInt id}) => RustLib.instance.api
    .crateApiStructureDesignerDocumentsApiCloseDocument(id: id);

/// Moves tab `id` to position `new_index` of the tab order (tab drag).
void moveDocument({required BigInt id, required int newIndex}) =>
    RustLib.instance.api.crateApiStructureDesignerDocumentsApiMoveDocument(
        id: id, newIndex: newIndex);

/// The CLI's `--document <path-or-id>` guard (D8): success when `spec` names
/// the active document, otherwise an error naming the active one.
APIResult checkDocumentGuard({required String spec}) => RustLib.instance.api
    .crateApiStructureDesignerDocumentsApiCheckDocumentGuard(spec: spec);
