// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../common_api_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'structure_designer_api_types.dart';

bool selectAtomOrBondByRay(
        {required APIVec3 rayStart,
        required APIVec3 rayDir,
        required SelectModifier selectModifier}) =>
    RustLib.instance.api
        .crateApiStructureDesignerEditAtomApiSelectAtomOrBondByRay(
            rayStart: rayStart, rayDir: rayDir, selectModifier: selectModifier);

void deleteSelectedAtomsAndBonds() => RustLib.instance.api
    .crateApiStructureDesignerEditAtomApiDeleteSelectedAtomsAndBonds();

void addAtomByRay(
        {required int atomicNumber,
        required APIVec3 planeNormal,
        required APIVec3 rayStart,
        required APIVec3 rayDir}) =>
    RustLib.instance.api.crateApiStructureDesignerEditAtomApiAddAtomByRay(
        atomicNumber: atomicNumber,
        planeNormal: planeNormal,
        rayStart: rayStart,
        rayDir: rayDir);

void replaceSelectedAtoms({required int atomicNumber}) => RustLib.instance.api
    .crateApiStructureDesignerEditAtomApiReplaceSelectedAtoms(
        atomicNumber: atomicNumber);

void editAtomUndo() =>
    RustLib.instance.api.crateApiStructureDesignerEditAtomApiEditAtomUndo();

void editAtomRedo() =>
    RustLib.instance.api.crateApiStructureDesignerEditAtomApiEditAtomRedo();

void transformSelected({required APITransform absTransform}) =>
    RustLib.instance.api.crateApiStructureDesignerEditAtomApiTransformSelected(
        absTransform: absTransform);

void drawBondByRay({required APIVec3 rayStart, required APIVec3 rayDir}) =>
    RustLib.instance.api.crateApiStructureDesignerEditAtomApiDrawBondByRay(
        rayStart: rayStart, rayDir: rayDir);

APIEditAtomTool? getActiveEditAtomTool() => RustLib.instance.api
    .crateApiStructureDesignerEditAtomApiGetActiveEditAtomTool();

bool setActiveEditAtomTool({required APIEditAtomTool tool}) =>
    RustLib.instance.api
        .crateApiStructureDesignerEditAtomApiSetActiveEditAtomTool(tool: tool);

void setEditAtomSelectedElement({required int atomicNumber}) => RustLib
    .instance.api
    .crateApiStructureDesignerEditAtomApiSetEditAtomSelectedElement(
        atomicNumber: atomicNumber);
