// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `empty`, `from_distribution`, `with_resolved`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `describe_field`, `isosurface_level_distribution`

/// Flutter entry point for [`isosurface_level_distribution`].
///
/// Refetch on **any** network-change notification, not only on selection
/// change: rewiring `field` or reloading the `.cube` must invalidate this, and
/// the failure mode — a correct-looking histogram belonging to the previous
/// field — is silent. The Flutter side gets that for free by calling this from
/// `build`, which Provider re-runs on every `notifyListeners`.
APIValueDistribution? getIsosurfaceLevelDistribution(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerFieldDistributionApiGetIsosurfaceLevelDistribution(
            scopePath: scopePath, nodeId: nodeId);

/// Why the editor has no distribution to plot. Three of the four are **normal**
/// states, not errors: the panel says which one it is in a caption and keeps its
/// shape (Part 5 §Empty states).
enum APIDistributionState {
  /// A real distribution over stored samples — the only state with data.
  available,

  /// Nothing is wired into the `field` pin.
  noField,

  /// The field has no stored samples (analytic), so there is nothing to bin.
  analyticField,

  /// The upstream has not produced a field yet, or failed. `message` says
  /// what, when there is anything to say.
  notEvaluated,
  ;
}

/// The `isosurface` level histogram, the cumulative curve, and the resolved
/// `(isovalue, fraction, basis)` for the node's current setting.
///
/// Bins are log-spaced over the field's **nonzero** magnitude range; exact zeros
/// have no bin and are reported by `zero_count` alone. Per-bin `mass` is
/// `Σ|v|^exponent`, never a sample count — a count-weighted plot is one vacuum
/// spike.
class APIValueDistribution {
  /// Which of the four states below the rest of this struct describes.
  final APIDistributionState state;

  /// Free-text detail for `NotEvaluated` (the upstream error). Empty otherwise.
  final String message;

  /// Bin edges as **magnitudes** (not logs), ascending. `bin_mass.len() + 1`
  /// entries. Empty unless `state` is `Available`.
  final Float64List binEdges;

  /// Mass in each bin, ascending in magnitude.
  final Float64List binMass;

  /// Share of the total mass at or above each edge, in `[0, 1]`, one entry per
  /// edge — the cumulative overlay, and the curve that relates the fraction
  /// slider's travel to the plot's `log10 |v|` axis.
  final Float64List cumulativeAtOrAbove;

  /// Smallest nonzero `|v|`. `0.0` for an all-zero field.
  final double nonzeroMin;

  /// Largest nonzero `|v|`. `0.0` for an all-zero field.
  final double nonzeroMax;

  /// Samples that are exactly zero — a line under the plot, never a bin.
  final BigInt zeroCount;

  /// `false` when the distribution was built from the log histogram rather
  /// than the exact sorted samples (a field above `EXACT_SAMPLE_LIMIT`), so
  /// the readout can say the numbers are accurate to a bin.
  final bool isExact;

  /// The isovalue the surface is actually drawn at. Meaningless unless
  /// `has_resolved_level`.
  final double resolvedLevel;

  /// What that isovalue encloses, as a share of `∫|v|`. Meaningless unless
  /// `has_resolved_fraction` — an analytic field has no distribution to read
  /// it from.
  final double resolvedFraction;

  /// Whether `resolved_level` means anything.
  final bool hasResolvedLevel;

  /// Whether `resolved_fraction` means anything.
  final bool hasResolvedFraction;

  /// The `Auto` basis label (`non-negative, density-like`, `signed field`, …),
  /// empty outside `Auto`. Rendered verbatim: `AutoBasis::label` is the only
  /// place these strings live, so the panel and the pin readout cannot drift.
  final String autoBasis;

  /// Whether the node's stored **`level`** still encloses exactly what the
  /// surface currently encloses.
  ///
  /// The mode dropdown converts: switching to `Absolute` writes the resolved
  /// magnitude so the surface does not move. Done unconditionally that would
  /// mangle a typed constant, because `iso → f → iso` is **not** a bijection
  /// (design §The two queries are not a bijection) — `iso_for_fraction` can
  /// only return a *stored sample*, so a `0.002` that went through fraction
  /// mode comes back as `0.00200034…`. When this flag is set the stored number
  /// already describes the current surface, so the switch keeps it verbatim
  /// and the round trip is lossless.
  ///
  /// The comparison is on the **enclosed fraction**, not on the magnitude:
  /// every isovalue between two adjacent samples encloses the same set, and
  /// "same set" is what "the surface did not move" means here.
  final bool storedLevelMatches;

  /// The same for the stored **`level_fraction`**, so a `Fraction → Absolute →
  /// Fraction` round trip returns the fraction the user typed rather than the
  /// tied-group overshoot.
  final bool storedFractionMatches;

  const APIValueDistribution({
    required this.state,
    required this.message,
    required this.binEdges,
    required this.binMass,
    required this.cumulativeAtOrAbove,
    required this.nonzeroMin,
    required this.nonzeroMax,
    required this.zeroCount,
    required this.isExact,
    required this.resolvedLevel,
    required this.resolvedFraction,
    required this.hasResolvedLevel,
    required this.hasResolvedFraction,
    required this.autoBasis,
    required this.storedLevelMatches,
    required this.storedFractionMatches,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      message.hashCode ^
      binEdges.hashCode ^
      binMass.hashCode ^
      cumulativeAtOrAbove.hashCode ^
      nonzeroMin.hashCode ^
      nonzeroMax.hashCode ^
      zeroCount.hashCode ^
      isExact.hashCode ^
      resolvedLevel.hashCode ^
      resolvedFraction.hashCode ^
      hasResolvedLevel.hashCode ^
      hasResolvedFraction.hashCode ^
      autoBasis.hashCode ^
      storedLevelMatches.hashCode ^
      storedFractionMatches.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIValueDistribution &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          message == other.message &&
          binEdges == other.binEdges &&
          binMass == other.binMass &&
          cumulativeAtOrAbove == other.cumulativeAtOrAbove &&
          nonzeroMin == other.nonzeroMin &&
          nonzeroMax == other.nonzeroMax &&
          zeroCount == other.zeroCount &&
          isExact == other.isExact &&
          resolvedLevel == other.resolvedLevel &&
          resolvedFraction == other.resolvedFraction &&
          hasResolvedLevel == other.hasResolvedLevel &&
          hasResolvedFraction == other.hasResolvedFraction &&
          autoBasis == other.autoBasis &&
          storedLevelMatches == other.storedLevelMatches &&
          storedFractionMatches == other.storedFractionMatches;
}
