// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'structure_designer_api_types.dart';

// These functions are ignored because they are not marked as `pub`: `design_dir`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `mechanosynth_data`, `mechanosynth_info`, `set_mechanosynth_data`

APIMechanosynthData? getMechanosynthData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerMechanosynthApiGetMechanosynthData(
            scopePath: scopePath, nodeId: nodeId);

void setMechanosynthNodeData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIMechanosynthData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerMechanosynthApiSetMechanosynthNodeData(
            scopePath: scopePath, nodeId: nodeId, data: data);

APIMechanosynthInfo? getMechanosynthInfo(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerMechanosynthApiGetMechanosynthInfo(
            scopePath: scopePath, nodeId: nodeId);
