// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `ns_to_ms`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

/// The most recent refresh, never coalesced — what the always-on status strip
/// shows. `None` before the first refresh of the session.
APIRefreshProfile? getLastRefreshProfile() => RustLib.instance.api
    .crateApiStructureDesignerProfilingApiGetLastRefreshProfile();

/// The bounded refresh history, oldest first. Consecutive lightweight rows are
/// already coalesced, so a gadget drag appears as one row with a count rather
/// than flushing the interesting refreshes out of the ring (D6).
List<APIRefreshProfile> getRefreshProfileHistory() => RustLib.instance.api
    .crateApiStructureDesignerProfilingApiGetRefreshProfileHistory();

/// Whether the opt-in per-node profiler is currently armed. Session state, not
/// a persisted preference: leaving it on across sessions would silently skew
/// later measurements (D2).
bool getEvalProfilingEnabled() => RustLib.instance.api
    .crateApiStructureDesignerProfilingApiGetEvalProfilingEnabled();

/// Arms or disarms the per-node profiler. Takes effect on the next evaluation
/// pass; the previously collected table stays readable until another profiled
/// pass replaces it.
void setEvalProfilingEnabled({required bool enabled}) => RustLib.instance.api
    .crateApiStructureDesignerProfilingApiSetEvalProfilingEnabled(
        enabled: enabled);

/// Whether the self-check is armed. Needs per-node profiling on as well — the
/// check lives in the profile.
bool getEvalSelfCheckEnabled() => RustLib.instance.api
    .crateApiStructureDesignerProfilingApiGetEvalSelfCheckEnabled();

/// Arms or disarms the self-check. Session state like the profiler toggle, and
/// for the same reason (D2): a check left on across sessions would quietly tax
/// every later measurement.
///
/// **Returns `false` when the request was refused** because the evaluation memo
/// is on (`doc/design_eval_memoization.md` D10's hard gate). Once a memo serves
/// the second request *from* the first result there is no second computation to
/// compare and the check passes vacuously, so arming it under a memo would
/// report a green that means nothing. The UI turns a `false` into an
/// explanation pointing at the memo switch rather than a silent no-op.
bool setEvalSelfCheckEnabled({required bool enabled}) => RustLib.instance.api
    .crateApiStructureDesignerProfilingApiSetEvalSelfCheckEnabled(
        enabled: enabled);

/// Whether the per-pass evaluation memo is on. **Defaults to `true`** — it is
/// the product's behaviour, unlike the profiler's opt-in toggle (D10).
bool getEvalMemoEnabled() => RustLib.instance.api
    .crateApiStructureDesignerProfilingApiGetEvalMemoEnabled();

/// Switches the evaluation memo on or off and forces one **full** refresh, so
/// the effect is visible immediately and the A/B comparison is between two
/// comparable passes (D10).
///
/// The refresh is not a convenience: a per-pass memo only shows its effect on
/// the *next* pass, and comparing a memo-off partial against a memo-on full
/// measures nothing.
///
/// Returns `true` when an armed self-check had to be disarmed to let the memo
/// run, so the panel can say so rather than leaving the user's diagnostic
/// silently switched off.
bool setEvalMemoEnabled({required bool enabled}) => RustLib.instance.api
    .crateApiStructureDesignerProfilingApiSetEvalMemoEnabled(enabled: enabled);

/// The most recent **profiled** pass's per-node table — read, never drained
/// (D6). `None` until a pass has run with profiling armed.
///
/// Deliberately not "the last refresh's": an unrelated lightweight tick, or a
/// refresh taken after the toggle went off, must not blank the panel.
APIEvalProfile? getLastEvalProfile() => RustLib.instance.api
    .crateApiStructureDesignerProfilingApiGetLastEvalProfile();

/// Arms the profiler and forces one **full** refresh, so successive readings
/// are comparable (D8b).
///
/// Without it the panel shows whatever partial refresh happened to run last,
/// and two measurements taken a minute apart measure different amounts of
/// work. The toggle is left **on** afterwards rather than restored, so the
/// *View* menu keeps telling the truth about what the next refresh will do.
void profileFullRefresh() => RustLib.instance.api
    .crateApiStructureDesignerProfilingApiProfileFullRefresh();

/// Flutter-facing mirror of [`CsgCacheDelta`].
class APICsgCacheCounts {
  final BigInt meshHits;
  final BigInt meshMisses;
  final BigInt sketchHits;
  final BigInt sketchMisses;

  const APICsgCacheCounts({
    required this.meshHits,
    required this.meshMisses,
    required this.sketchHits,
    required this.sketchMisses,
  });

  @override
  int get hashCode =>
      meshHits.hashCode ^
      meshMisses.hashCode ^
      sketchHits.hashCode ^
      sketchMisses.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APICsgCacheCounts &&
          runtimeType == other.runtimeType &&
          meshHits == other.meshHits &&
          meshMisses == other.meshMisses &&
          sketchHits == other.sketchHits &&
          sketchMisses == other.sketchMisses;
}

/// The per-node breakdown of one profiled evaluation pass.
class APIEvalProfile {
  final BigInt totalEvaluations;

  /// Summed self time over every record — the figure to compare against the
  /// refresh's `evalMs` phase.
  final double totalSelfMs;

  /// Total result requests (Phase 3). Equal to `total_evaluations` until the
  /// memo lands.
  final BigInt totalLookups;

  /// Distinct evaluation environments the pass visited — and, since the key
  /// carries the node and `decorate` too, the **number of entries a perfect
  /// memo would hold at peak**. The memo's memory question, measured before a
  /// line of it is written.
  final BigInt totalDistinctEnvs;

  /// `total_lookups / total_distinct_envs`. Shown next to — never instead of
  /// — the per-node breakdown: a pass that is globally 2.5x can be 11x on
  /// `materialize` and 1.0 on body nodes, and only the breakdown says where a
  /// memo would pay (D10).
  final double redundancyFactor;

  /// Summed `wasted_ms` over the rows the memo would actually cache — rows
  /// flagged uncacheable are excluded rather than inflating the projection.
  final double projectedSavingMs;

  /// Environment tracking stopped at its ceiling, so `total_distinct_envs` is
  /// a floor and the redundancy numbers are upper bounds. Reported rather than
  /// silently capped.
  final bool envsTruncated;

  /// Whether the D11 equal-key/equal-result self-check ran for this pass.
  final bool selfCheckRan;

  /// Self-check sampling hit its ceiling, so a clean result covers only the
  /// environments seen before that point rather than the whole pass.
  final bool selfCheckTruncated;

  /// What it found. Empty is the expected outcome; a non-empty list means the
  /// environment key is missing an input — a wrong number now, and a wrong
  /// result once the memo keys on it.
  final List<APISelfCheckViolation> selfCheckViolations;

  /// **The acceptance criterion of `doc/design_eval_memoization.md`, as one
  /// number**: rows that re-evaluated within a single environment with no
  /// flag excusing it.
  ///
  /// Zero with the memo working. Computed in the domain rather than by
  /// filtering `by_node` in Dart so the population it is counted over —
  /// unflagged rows only — has exactly one definition.
  final BigInt unmemoizedOffenders;
  final List<APINodeProfileRecord> byNode;
  final List<APINodeTypeProfileRecord> byNodeType;

  const APIEvalProfile({
    required this.totalEvaluations,
    required this.totalSelfMs,
    required this.totalLookups,
    required this.totalDistinctEnvs,
    required this.redundancyFactor,
    required this.projectedSavingMs,
    required this.envsTruncated,
    required this.selfCheckRan,
    required this.selfCheckTruncated,
    required this.selfCheckViolations,
    required this.unmemoizedOffenders,
    required this.byNode,
    required this.byNodeType,
  });

  @override
  int get hashCode =>
      totalEvaluations.hashCode ^
      totalSelfMs.hashCode ^
      totalLookups.hashCode ^
      totalDistinctEnvs.hashCode ^
      redundancyFactor.hashCode ^
      projectedSavingMs.hashCode ^
      envsTruncated.hashCode ^
      selfCheckRan.hashCode ^
      selfCheckTruncated.hashCode ^
      selfCheckViolations.hashCode ^
      unmemoizedOffenders.hashCode ^
      byNode.hashCode ^
      byNodeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIEvalProfile &&
          runtimeType == other.runtimeType &&
          totalEvaluations == other.totalEvaluations &&
          totalSelfMs == other.totalSelfMs &&
          totalLookups == other.totalLookups &&
          totalDistinctEnvs == other.totalDistinctEnvs &&
          redundancyFactor == other.redundancyFactor &&
          projectedSavingMs == other.projectedSavingMs &&
          envsTruncated == other.envsTruncated &&
          selfCheckRan == other.selfCheckRan &&
          selfCheckTruncated == other.selfCheckTruncated &&
          selfCheckViolations == other.selfCheckViolations &&
          unmemoizedOffenders == other.unmemoizedOffenders &&
          byNode == other.byNode &&
          byNodeType == other.byNodeType;
}

/// Flutter-facing mirror of [`MemoCounts`]: one refresh's evaluation-memo
/// activity.
///
/// Byte counts stay `u64` rather than becoming megabytes here: the panel
/// formats them, and a rounding decision made at the FFI boundary cannot be
/// undone by the code that has to present it.
class APIMemoCounts {
  /// `false` means the memo was switched off for this pass — which is not the
  /// same as "on, but this design had nothing to share", and the panel must
  /// not render the two identically.
  final bool enabled;

  /// Entries held at the high-water mark. Compare against
  /// [`APIEvalProfile::total_distinct_envs`], which predicts it.
  final BigInt peakEntries;
  final BigInt peakBytes;
  final BigInt endEntries;
  final BigInt endBytes;
  final BigInt budgetBytes;
  final BigInt hits;
  final BigInt misses;

  /// Misses on a key the memo had held earlier — work redone because the
  /// budget was too small.
  final BigInt evictedMisses;

  /// Entries the LRU dropped because the budget was exceeded. **The Phase 5
  /// trigger**: any eviction at all on an ordinary design.
  final BigInt lruEvictions;

  /// Entries retired because their body iteration ended (D3). Kept apart from
  /// `lru_evictions` because they mean opposite things — one is the design
  /// working, the other is the budget being too small.
  final BigInt epochDrops;

  /// The deliberate exclusions firing (subnetwork arm, iterators,
  /// re-entrancy), as a total.
  final BigInt declinedInserts;

  /// Time inside the memo's insert path, dominated by the size estimator's
  /// recursive walk. Shown so it can be ruled out at a glance rather than
  /// eroding the win invisibly.
  final double insertMs;

  /// The evicted-key tracking hit its ceiling, so `evicted_misses` is a floor.
  final bool insertedTrackingTruncated;

  const APIMemoCounts({
    required this.enabled,
    required this.peakEntries,
    required this.peakBytes,
    required this.endEntries,
    required this.endBytes,
    required this.budgetBytes,
    required this.hits,
    required this.misses,
    required this.evictedMisses,
    required this.lruEvictions,
    required this.epochDrops,
    required this.declinedInserts,
    required this.insertMs,
    required this.insertedTrackingTruncated,
  });

  @override
  int get hashCode =>
      enabled.hashCode ^
      peakEntries.hashCode ^
      peakBytes.hashCode ^
      endEntries.hashCode ^
      endBytes.hashCode ^
      budgetBytes.hashCode ^
      hits.hashCode ^
      misses.hashCode ^
      evictedMisses.hashCode ^
      lruEvictions.hashCode ^
      epochDrops.hashCode ^
      declinedInserts.hashCode ^
      insertMs.hashCode ^
      insertedTrackingTruncated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIMemoCounts &&
          runtimeType == other.runtimeType &&
          enabled == other.enabled &&
          peakEntries == other.peakEntries &&
          peakBytes == other.peakBytes &&
          endEntries == other.endEntries &&
          endBytes == other.endBytes &&
          budgetBytes == other.budgetBytes &&
          hits == other.hits &&
          misses == other.misses &&
          evictedMisses == other.evictedMisses &&
          lruEvictions == other.lruEvictions &&
          epochDrops == other.epochDrops &&
          declinedInserts == other.declinedInserts &&
          insertMs == other.insertMs &&
          insertedTrackingTruncated == other.insertedTrackingTruncated;
}

/// One row of the profiler panel's **By node** table: an aggregate over every
/// evaluation of one node in one home network during one pass.
///
/// `lookups` and `wasted_ms` are Phase 3 fields that sit **alongside**
/// `evaluations` rather than re-interpreting it (D8b). Before the evaluation
/// memo lands `lookups == evaluations` exactly; afterwards the difference is the
/// memo's hit count, and a column that quietly changed meaning at that point is
/// how a regression would hide.
class APINodeProfileRecord {
  /// Human-readable address: `"main/fold#12/add#3 (mysum)"`.
  final String label;
  final String nodeTypeName;

  /// Click-to-jump target — the network the node lives in. For a node inside
  /// a custom network this is that network, not the one being profiled.
  final String hostNetwork;

  /// Click-to-jump target — the HOF-body chain within `host_network`.
  final Uint64List scopePath;

  /// Click-to-jump target — the node.
  final BigInt nodeId;

  /// False only for a lazily-evaluated HOF body whose address could not be
  /// pinned down (see `NodeLocation::navigable`). Such a row is still
  /// measured and still rolls up by type; the panel just renders it
  /// non-clickable rather than offering a jump that lands nowhere.
  final bool navigable;
  final BigInt evaluations;

  /// Times a result for this node was **requested**. Equals `evaluations`
  /// until the memo lands.
  final BigInt lookups;

  /// How many distinct evaluation environments those requests spanned (D9).
  /// The denominator that makes the redundancy factor honest: a `map` body
  /// node run once per element over 3 elements has 3 distinct environments
  /// and is not redundant at all.
  final BigInt distinctEnvs;

  /// `lookups / distinct_envs` — the per-node redundancy factor. `1.0` means
  /// every request was a genuinely different environment.
  final double redundancyFactor;

  /// Self time a perfect memo would avoid, in ms. **The actionable column.**
  final double wastedMs;

  /// The node produced an iterator, which `doc/design_eval_memoization.md` D4
  /// deliberately does not cache — so its `wasted_ms` is not an available
  /// saving.
  final bool producedIterator;

  /// The re-entrancy backstop fired on this node (a wire cycle escaped
  /// validation); D9 there forbids memoizing under it, so again `wasted_ms`
  /// is not collectable.
  final bool underReentrancyBackstop;

  /// A custom-network instance requested through `evaluate`'s single-pin arm,
  /// which D2 forbids the memo from inserting from. Such a row shows
  /// `evaluations == lookups` permanently with the memo working perfectly;
  /// unflagged, every subnetwork in every design would read as a memo bug.
  final bool subnetwork;

  /// The memo held this node's entry earlier in the pass and the LRU dropped
  /// it, so the work was redone (D6). Distinguishes memory pressure from a
  /// correctness bug.
  final bool evicted;

  /// Time in this node's own `eval`, with its dependencies' time subtracted.
  final double selfMs;

  /// Wall time including everything this node pulled. A custom-node instance
  /// legitimately shows ~zero `self_ms` against a large `total_ms`: it
  /// delegates to its network's return node.
  final double totalMs;

  const APINodeProfileRecord({
    required this.label,
    required this.nodeTypeName,
    required this.hostNetwork,
    required this.scopePath,
    required this.nodeId,
    required this.navigable,
    required this.evaluations,
    required this.lookups,
    required this.distinctEnvs,
    required this.redundancyFactor,
    required this.wastedMs,
    required this.producedIterator,
    required this.underReentrancyBackstop,
    required this.subnetwork,
    required this.evicted,
    required this.selfMs,
    required this.totalMs,
  });

  @override
  int get hashCode =>
      label.hashCode ^
      nodeTypeName.hashCode ^
      hostNetwork.hashCode ^
      scopePath.hashCode ^
      nodeId.hashCode ^
      navigable.hashCode ^
      evaluations.hashCode ^
      lookups.hashCode ^
      distinctEnvs.hashCode ^
      redundancyFactor.hashCode ^
      wastedMs.hashCode ^
      producedIterator.hashCode ^
      underReentrancyBackstop.hashCode ^
      subnetwork.hashCode ^
      evicted.hashCode ^
      selfMs.hashCode ^
      totalMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APINodeProfileRecord &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          nodeTypeName == other.nodeTypeName &&
          hostNetwork == other.hostNetwork &&
          scopePath == other.scopePath &&
          nodeId == other.nodeId &&
          navigable == other.navigable &&
          evaluations == other.evaluations &&
          lookups == other.lookups &&
          distinctEnvs == other.distinctEnvs &&
          redundancyFactor == other.redundancyFactor &&
          wastedMs == other.wastedMs &&
          producedIterator == other.producedIterator &&
          underReentrancyBackstop == other.underReentrancyBackstop &&
          subnetwork == other.subnetwork &&
          evicted == other.evicted &&
          selfMs == other.selfMs &&
          totalMs == other.totalMs;
}

/// One row of the **By node type** table — a roll-up of every
/// [`APINodeProfileRecord`] sharing a type name. Both tables come from one map,
/// so their totals agree by construction.
class APINodeTypeProfileRecord {
  final String nodeTypeName;

  /// How many distinct nodes of this type were evaluated.
  final BigInt nodes;
  final BigInt evaluations;
  final double selfMs;
  final double totalMs;

  const APINodeTypeProfileRecord({
    required this.nodeTypeName,
    required this.nodes,
    required this.evaluations,
    required this.selfMs,
    required this.totalMs,
  });

  @override
  int get hashCode =>
      nodeTypeName.hashCode ^
      nodes.hashCode ^
      evaluations.hashCode ^
      selfMs.hashCode ^
      totalMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APINodeTypeProfileRecord &&
          runtimeType == other.runtimeType &&
          nodeTypeName == other.nodeTypeName &&
          nodes == other.nodes &&
          evaluations == other.evaluations &&
          selfMs == other.selfMs &&
          totalMs == other.totalMs;
}

/// Flutter-facing mirror of [`RefreshMode`]. Which of the three refresh paths
/// produced a profile row — the tag that makes a 40 ms drag tick and a 1.8 s
/// node activation distinguishable at a glance.
enum APIRefreshMode {
  lightweight,
  partial,
  full,
  ;
}

/// Flutter-facing mirror of [`RefreshProfile`]: one refresh broken into its
/// phases, all in milliseconds.
///
/// `evalMs` and `backgroundMs` are `null` — never `0.0` — when the refresh ran
/// no such phase at all. A lightweight refresh enters no evaluation pass and
/// skips the background mesh rebuild; rendering either as `0.00` would read as
/// "that phase is free", which is precisely the wrong conclusion (D6/D8a).
class APIRefreshProfile {
  final APIRefreshMode mode;

  /// Evaluation of the displayed roots. `None` on a lightweight refresh.
  final double? evalMs;

  /// Scene-dependent node data refresh.
  final double sceneDependentMs;

  /// Gadget rebuild + tessellatable.
  final double gadgetMs;

  /// Scene tessellation.
  final double tessellateMs;

  /// CPU-side mesh upload to the renderer.
  final double gpuUploadMs;

  /// Background coordinate-system mesh rebuild. `None` when skipped.
  final double? backgroundMs;

  /// Wall time of the whole Rust-side refresh. The Dart-side stopwatch
  /// brackets this one, and the difference is the FFI overhead (D7).
  final double totalMs;

  /// How many refreshes this row represents — always 1 for the "last
  /// refresh" reading, and > 1 for a history row that coalesced a burst of
  /// consecutive lightweight ticks (in which case the timings above are
  /// means over the burst).
  final int count;

  /// Worst `total_ms` among the refreshes coalesced into this row.
  final double maxTotalMs;

  /// CSG conversion-cache activity this refresh caused (D12). Shown *beside*
  /// the phase totals, never folded into node time — the time itself is
  /// charged to the node that triggered the conversion, and what these
  /// counters add is why two otherwise identical refreshes differ.
  final APICsgCacheCounts csgCache;

  /// Whether this refresh's evaluation pass was profiled per node. The table
  /// itself is fetched separately by [`get_last_eval_profile`] — a history
  /// row carries the flag only, so listing 20 rows does not marshal 20
  /// tables across the FFI boundary.
  final bool hasNodeStats;

  /// What the per-pass evaluation memo did during this refresh, and whether
  /// it was on at all (`doc/design_eval_memoization.md` D10).
  ///
  /// Carried **per row**, not fetched separately, because the comparison this
  /// exists for is two rows side by side — one taken with the memo off, one
  /// with it on. A single "current state" reading could not express that.
  final APIMemoCounts memo;

  const APIRefreshProfile({
    required this.mode,
    this.evalMs,
    required this.sceneDependentMs,
    required this.gadgetMs,
    required this.tessellateMs,
    required this.gpuUploadMs,
    this.backgroundMs,
    required this.totalMs,
    required this.count,
    required this.maxTotalMs,
    required this.csgCache,
    required this.hasNodeStats,
    required this.memo,
  });

  @override
  int get hashCode =>
      mode.hashCode ^
      evalMs.hashCode ^
      sceneDependentMs.hashCode ^
      gadgetMs.hashCode ^
      tessellateMs.hashCode ^
      gpuUploadMs.hashCode ^
      backgroundMs.hashCode ^
      totalMs.hashCode ^
      count.hashCode ^
      maxTotalMs.hashCode ^
      csgCache.hashCode ^
      hasNodeStats.hashCode ^
      memo.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APIRefreshProfile &&
          runtimeType == other.runtimeType &&
          mode == other.mode &&
          evalMs == other.evalMs &&
          sceneDependentMs == other.sceneDependentMs &&
          gadgetMs == other.gadgetMs &&
          tessellateMs == other.tessellateMs &&
          gpuUploadMs == other.gpuUploadMs &&
          backgroundMs == other.backgroundMs &&
          totalMs == other.totalMs &&
          count == other.count &&
          maxTotalMs == other.maxTotalMs &&
          csgCache == other.csgCache &&
          hasNodeStats == other.hasNodeStats &&
          memo == other.memo;
}

/// Flutter-facing mirror of [`SelfCheckViolation`]: two evaluations that shared
/// an environment key produced different results.
class APISelfCheckViolation {
  final String label;
  final String first;
  final String later;

  const APISelfCheckViolation({
    required this.label,
    required this.first,
    required this.later,
  });

  @override
  int get hashCode => label.hashCode ^ first.hashCode ^ later.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is APISelfCheckViolation &&
          runtimeType == other.runtimeType &&
          label == other.label &&
          first == other.first &&
          later == other.later;
}
