// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'structure_designer_api_types.dart';

// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `proxy_node_data`, `proxy_node_stats`, `set_proxy_node_data`

APIProxyData? getProxyData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api.crateApiStructureDesignerProxyApiGetProxyData(
        scopePath: scopePath, nodeId: nodeId);

void setProxyData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIProxyData data}) =>
    RustLib.instance.api.crateApiStructureDesignerProxyApiSetProxyData(
        scopePath: scopePath, nodeId: nodeId, data: data);

APIProxyStats? getProxyStats() =>
    RustLib.instance.api.crateApiStructureDesignerProxyApiGetProxyStats();
