// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../common_api_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'structure_designer_api_types.dart';
import 'structure_designer_preferences.dart';

// These functions are ignored because they are not marked as `pub`: `alignment_to_api`, `api_closure_kind_to_closure_kind`, `api_field_editor_hint_to_core`, `api_literal_to_text_value`, `api_to_type_args`, `atom_symbol`, `build_derived_shape_view`, `build_node_view`, `build_wires_for_network`, `build_zone_view`, `closure_kind_to_api_closure_kind`, `compute_last_selected_result_atom_id`, `compute_selection_measurement`, `crystal_system_to_string`, `data_type_to_simple_param_type`, `field_editor_hint_to_api`, `network_result_to_api_literal`, `param_element_color_u32`, `rows_f64_to_vecs`, `rows_i32_to_vecs`, `text_value_to_api_literal`, `type_args_to_api`, `vecs_to_rows_f64`, `vecs_to_rows_i32`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `api_data_type_to_data_type`, `data_type_to_api_data_type`

NodeNetworkView? getNodeNetworkView() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetNodeNetworkView();

/// Move a node. The targeted network is identified by `scope_path` — empty
/// means the active top-level network (existing behavior); a non-empty path
/// names a chain of HOF body owners to descend through via `Node.zone_mut()`.
/// Phase U2 of `doc/design_zones_ui.md` plumbs the parameter through every
/// mutation API.
void moveNode(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIVec2 position}) =>
    RustLib.instance.api.crateApiStructureDesignerStructureDesignerApiMoveNode(
        scopePath: scopePath, nodeId: nodeId, position: position);

/// Add a node to the network identified by `scope_path` (empty = active
/// top-level network; non-empty = walk `Node.zone` down the chain). Phase U2
/// plumbs the parameter through; body-scope adds run a simpler path without
/// the top-level orchestration (undo / display policy / drag-source
/// adapter) — those re-enter under a scope-aware code path in U4. See
/// `doc/design_zones_ui.md`.
BigInt addNode(
        {required Uint64List scopePath,
        required String nodeTypeName,
        required APIVec2 position,
        APIDragSource? dragSource}) =>
    RustLib.instance.api.crateApiStructureDesignerStructureDesignerApiAddNode(
        scopePath: scopePath,
        nodeTypeName: nodeTypeName,
        position: position,
        dragSource: dragSource);

/// Duplicate a node within `scope_path`'s network. Phase U4 — body-scope
/// dispatch routes through `duplicate_node_scoped`.
BigInt duplicateNode({required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiDuplicateNode(
            scopePath: scopePath, nodeId: nodeId);

bool canConnectNodes(
        {required Uint64List scopePath,
        required BigInt sourceNodeId,
        required int sourceOutputPinIndex,
        required BigInt destNodeId,
        required BigInt destParamIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiCanConnectNodes(
            scopePath: scopePath,
            sourceNodeId: sourceNodeId,
            sourceOutputPinIndex: sourceOutputPinIndex,
            destNodeId: destNodeId,
            destParamIndex: destParamIndex);

void connectNodes(
        {required Uint64List scopePath,
        required BigInt sourceNodeId,
        required int sourceOutputPinIndex,
        required BigInt destNodeId,
        required BigInt destParamIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiConnectNodes(
            scopePath: scopePath,
            sourceNodeId: sourceNodeId,
            sourceOutputPinIndex: sourceOutputPinIndex,
            destNodeId: destNodeId,
            destParamIndex: destParamIndex);

/// General-shape wire-creation entry point for cross-scope wires. Used by
/// zones UI phase U5 to author captures (depth ≥ 1) and iteration-value
/// references (`ZoneInput` source). For local-scope `NodeOutput` wires the
/// existing [`connect_nodes`] is equivalent and slightly cheaper; for body-
/// return wires use [`connect_zone_output_wire`].
///
/// `dest_scope_path` is the network where the wire is stored — the body
/// containing the destination node. `source_scope_depth` measures how many
/// ancestor frames up from that storage scope the source lives.
void connectWire(
        {required Uint64List destScopePath,
        required BigInt sourceNodeId,
        required APISourcePin sourcePin,
        required int sourceScopeDepth,
        required BigInt destNodeId,
        required BigInt destParamIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiConnectWire(
            destScopePath: destScopePath,
            sourceNodeId: sourceNodeId,
            sourcePin: sourcePin,
            sourceScopeDepth: sourceScopeDepth,
            destNodeId: destNodeId,
            destParamIndex: destParamIndex);

/// Predicate pair for [`connect_wire`]. Returns `true` when a cross-scope
/// wire with this shape is type-compatible and structurally valid.
bool canConnectWire(
        {required Uint64List destScopePath,
        required BigInt sourceNodeId,
        required APISourcePin sourcePin,
        required int sourceScopeDepth,
        required BigInt destNodeId,
        required BigInt destParamIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiCanConnectWire(
            destScopePath: destScopePath,
            sourceNodeId: sourceNodeId,
            sourcePin: sourcePin,
            sourceScopeDepth: sourceScopeDepth,
            destNodeId: destNodeId,
            destParamIndex: destParamIndex);

/// Connect a body-return wire: source is a body node, destination is the
/// containing HOF's zone-output pin. `body_scope_path` identifies the body
/// (the last element is the HOF id whose `zone_output_arguments` receives
/// the wire). Phase U4 — see `doc/design_zones_ui.md` §"Wire-creation API
/// generalisation".
void connectZoneOutputWire(
        {required Uint64List bodyScopePath,
        required BigInt sourceNodeId,
        required int sourceOutputPinIndex,
        required BigInt zoneOutputIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiConnectZoneOutputWire(
            bodyScopePath: bodyScopePath,
            sourceNodeId: sourceNodeId,
            sourceOutputPinIndex: sourceOutputPinIndex,
            zoneOutputIndex: zoneOutputIndex);

/// Auto-connects a source pin to the first compatible pin on a target node.
///
/// - `source_node_id`: The node where the wire was dragged from
/// - `source_pin_index`: The pin index on the source node
/// - `source_is_output`: true if dragging from output pin, false if from input pin
/// - `target_node_id`: The newly created node to connect to
///
/// Returns true if a connection was made, false otherwise.
bool autoConnectToNode(
        {required Uint64List scopePath,
        required BigInt sourceNodeId,
        required int sourcePinIndex,
        required bool sourceIsOutput,
        required BigInt targetNodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiAutoConnectToNode(
            scopePath: scopePath,
            sourceNodeId: sourceNodeId,
            sourcePinIndex: sourcePinIndex,
            sourceIsOutput: sourceIsOutput,
            targetNodeId: targetNodeId);

/// Returns all compatible pins on the target node for auto-connection.
/// Each element contains (pin_index, pin_name, data_type_string).
/// When source_is_output is true, returns compatible INPUT pins on target.
/// When source_is_output is false, returns the OUTPUT pin if compatible.
List<(int, String, String)> getCompatiblePinsForAutoConnect(
        {required Uint64List scopePath,
        required BigInt sourceNodeId,
        required int sourcePinIndex,
        required bool sourceIsOutput,
        required BigInt targetNodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetCompatiblePinsForAutoConnect(
            scopePath: scopePath,
            sourceNodeId: sourceNodeId,
            sourcePinIndex: sourcePinIndex,
            sourceIsOutput: sourceIsOutput,
            targetNodeId: targetNodeId);

List<APINodeCategoryView>? getNodeTypeViews() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetNodeTypeViews();

/// Returns node types that have at least one pin compatible with the given type.
///
/// - `source_type_str`: The data type being dragged (serialized string, e.g., "Blueprint", "Float")
/// - `dragging_from_output`: true if dragging from output pin, false if from input pin
///
/// When dragging from OUTPUT: find nodes with compatible INPUT pins
/// When dragging from INPUT: find nodes with compatible OUTPUT pins
List<APINodeCategoryView>? getCompatibleNodeTypes(
        {required String sourceTypeStr, required bool draggingFromOutput}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetCompatibleNodeTypes(
            sourceTypeStr: sourceTypeStr,
            draggingFromOutput: draggingFromOutput);

List<String>? getNodeNetworkNames() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetNodeNetworkNames();

/// Returns the deliberately-created empty-folder paths (sorted). The tree view
/// merges these with the folders implied by entity names. See
/// `doc/design_empty_folders.md`.
List<String>? getFolderNames() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetFolderNames();

/// Returns every **user-declared** record type def name in the project,
/// sorted alphabetically. Used by the user-types panel so built-in defs are
/// not listed there. Dropdowns (type selector, `record_construct` /
/// `record_destructure` / `product` editors) should call
/// `get_all_record_type_def_names` instead so they see built-ins too.
List<String>? getRecordTypeDefNames() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetRecordTypeDefNames();

/// Returns every record type def name in the project (user-declared plus
/// built-in), sorted alphabetically. Used by the Flutter type-selector
/// Record branch and by the `record_construct` / `record_destructure` /
/// `product` node-property dropdowns. See
/// `doc/design_atom_replace_rules_input.md` Phase A.
List<String>? getAllRecordTypeDefNames() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetAllRecordTypeDefNames();

/// Returns every built-in record type def name, sorted alphabetically.
/// Used by Flutter-side namespace-collision checks so the UI can pre-validate
/// before round-tripping to Rust. See
/// `doc/design_atom_replace_rules_input.md` Phase A.
List<String>? getBuiltInRecordTypeDefNames() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetBuiltInRecordTypeDefNames();

/// Returns the full record type def for `name`, or `None` if the name is
/// not registered. Used by the schema editor in the user-types panel.
APIRecordTypeDef? getRecordTypeDef({required String name}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiGetRecordTypeDef(name: name);

/// Adds a new record type def with `name` and an empty field list.
/// Empty record defs are valid (top of the subtype lattice).
APIResult addRecordTypeDef({required String name}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiAddRecordTypeDef(name: name);

/// Deletes the record type def with the given name. Fails (with a `Referenced`
/// error listing the offenders) if any network or other record def still
/// references it — mirroring network / namespace deletion.
APIResult deleteRecordTypeDef({required String name}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiDeleteRecordTypeDef(
        name: name);

/// Renames a record type def. Walks every embedded `Named(old_name)`
/// reference in the project and rewrites it to `Named(new_name)`. No wires
/// are disconnected — every reference resolves to the same schema, just
/// under a new name.
APIResult renameRecordTypeDef(
        {required String oldName, required String newName}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiRenameRecordTypeDef(
            oldName: oldName, newName: newName);

/// Replaces the field list of an existing record type def. Authored field
/// order is preserved; cycle introduction is rejected. Networks are
/// repaired afterward so `record_construct` / `record_destructure` /
/// `product` pin layouts re-derive and now-incompatible wires are dropped.
APIResult updateRecordTypeDef(
        {required String name, required List<APIRecordTypeField> fields}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiUpdateRecordTypeDef(
            name: name, fields: fields);

/// Checks if a node type name corresponds to a custom node (i.e., a user-defined node network).
/// Returns false if the CAD instance is not available.
bool isCustomNodeType({required String nodeTypeName}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiIsCustomNodeType(
        nodeTypeName: nodeTypeName);

/// Gets the description of the active node network
String? getActiveNetworkDescription() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetActiveNetworkDescription();

/// Sets the description of the active node network
void setActiveNetworkDescription({required String description}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiSetActiveNetworkDescription(
        description: description);

/// Gets the summary of the active node network
String? getActiveNetworkSummary() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetActiveNetworkSummary();

/// Sets the summary of the active node network
/// Pass None or empty string to clear the summary
void setActiveNetworkSummary({String? summary}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSetActiveNetworkSummary(
        summary: summary);

/// Gets the description of a specific node network
String? getNetworkDescription({required String networkName}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiGetNetworkDescription(
        networkName: networkName);

List<APINetworkWithValidationErrors>? getNodeNetworksWithValidation() => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiGetNodeNetworksWithValidation();

/// Add a node network with an auto-generated unique name and activate it.
/// Returns the generated name so the Flutter side can select the new network
/// (the network registry is a HashMap, so list order is not reliable — issue
/// #315).
String addNewNodeNetwork() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiAddNewNodeNetwork();

/// Add a node network with an auto-generated unique name under `namespace`
/// (a dot-delimited prefix; empty string = root) and activate it. Returns the
/// generated qualified name so the Flutter side can select the new network.
String addNewNodeNetworkInNamespace({required String namespace}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiAddNewNodeNetworkInNamespace(
        namespace: namespace);

/// Add a record type def with an auto-generated unique name under `namespace`
/// (a dot-delimited prefix; empty string = root) and activate it. Returns the
/// generated qualified name, or an empty string on failure.
String addNewRecordTypeDefInNamespace({required String namespace}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiAddNewRecordTypeDefInNamespace(
        namespace: namespace);

/// Add a node network with a specific name.
/// Returns success/error. Auto-activates the new network.
APIResult addNodeNetworkWithName({required String name}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiAddNodeNetworkWithName(
        name: name);

void setActiveNodeNetwork({required String nodeNetworkName}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiSetActiveNodeNetwork(
        nodeNetworkName: nodeNetworkName);

/// Navigates back in node network history
bool navigateBack() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiNavigateBack();

/// Navigates forward in node network history
bool navigateForward() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiNavigateForward();

/// Checks if we can navigate backward in node network history
bool canNavigateBack() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiCanNavigateBack();

/// Checks if we can navigate forward in node network history
bool canNavigateForward() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiCanNavigateForward();

bool renameNodeNetwork({required String oldName, required String newName}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiRenameNodeNetwork(
            oldName: oldName, newName: newName);

APIResult deleteNodeNetwork({required String networkName}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiDeleteNodeNetwork(
            networkName: networkName);

/// Duplicate a named node network under a fresh unique name (`<name>_copy`,
/// then `<name>_copy_2`, …). The copy is a shallow duplicate: inline zone
/// bodies are copied; references to other named networks stay references.
/// Auto-activates the new copy. Returns success/error.
APIResult duplicateNodeNetwork({required String sourceName}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiDuplicateNodeNetwork(
        sourceName: sourceName);

bool renameNamespace({required String oldPrefix, required String newPrefix}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiRenameNamespace(
            oldPrefix: oldPrefix, newPrefix: newPrefix);

/// Read-only preview of moving/renaming the namespace `old_prefix` to
/// `new_prefix` (empty `new_prefix` => promote contents to the root). Returns
/// the full list of affected networks with their resulting names plus
/// conflict/validity flags so the move-namespace dialog can show the user
/// exactly what will happen — and whether it is allowed — before committing.
/// Does not mutate state.
APINamespaceRenamePreview previewNamespaceRename(
        {required String oldPrefix, required String newPrefix}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiPreviewNamespaceRename(
            oldPrefix: oldPrefix, newPrefix: newPrefix);

/// Read-only preview of moving/renaming a single leaf `old_name` (a node
/// network **or** a record type def) to the fully-qualified `new_name`. The
/// kind is detected by the backend (`compute_leaf_rename`), so the move dialog
/// can render both kinds uniformly. Returns the same single-item preview shape
/// as `preview_namespace_rename`. Does not mutate state.
APINamespaceRenamePreview previewLeafRename(
        {required String oldName, required String newName}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiPreviewLeafRename(
            oldName: oldName, newName: newName);

/// The user record type def currently open in the schema editor, or `None`.
/// Backend-owned source of truth (see `doc/design_hierarchical_records.md` §8);
/// the Flutter model mirrors this in `refreshFromKernel` so the selection
/// survives undo/redo of a record rename/move/delete.
String? getActiveRecordDefName() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetActiveRecordDefName();

/// Set the active record def (the one open in the schema editor). Pass `None`
/// to clear the selection (fall back to the network editor). This is plain
/// selection state — not undoable — but it is backend-owned so undo/redo of
/// record rename/delete can remap/clear it correctly.
void setActiveRecordDefName({String? name}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSetActiveRecordDefName(
        name: name);

APIResult deleteNamespace({required String prefix}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiDeleteNamespace(
        prefix: prefix);

/// Create an empty folder at `path` (dot-delimited, e.g. `"Physics.Mechanics"`).
/// Returns success/error (collision or invalid name). See
/// `doc/design_empty_folders.md`.
APIResult addFolder({required String path}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiAddFolder(path: path);

void setNodeDisplay(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required bool isDisplayed}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetNodeDisplay(
            scopePath: scopePath, nodeId: nodeId, isDisplayed: isDisplayed);

void toggleOutputPinDisplay(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required int pinIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiToggleOutputPinDisplay(
            scopePath: scopePath, nodeId: nodeId, pinIndex: pinIndex);

bool selectNode({required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSelectNode(
            scopePath: scopePath, nodeId: nodeId);

bool selectWire(
        {required Uint64List scopePath,
        required BigInt sourceNodeId,
        required int sourceOutputPinIndex,
        required BigInt destinationNodeId,
        required BigInt destinationArgumentIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSelectWire(
            scopePath: scopePath,
            sourceNodeId: sourceNodeId,
            sourceOutputPinIndex: sourceOutputPinIndex,
            destinationNodeId: destinationNodeId,
            destinationArgumentIndex: destinationArgumentIndex);

void clearSelection({required Uint64List scopePath}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiClearSelection(
        scopePath: scopePath);

/// Clear selection in every scope reachable from the active top-level
/// network. Used when the user clicks empty top-level space so an active body
/// node doesn't keep its `.active` flag. Phase U4.
void clearSelectionAllScopes() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiClearSelectionAllScopes();

bool toggleNodeSelection(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiToggleNodeSelection(
            scopePath: scopePath, nodeId: nodeId);

bool addNodeToSelection(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiAddNodeToSelection(
            scopePath: scopePath, nodeId: nodeId);

bool selectNodes(
        {required Uint64List scopePath, required Uint64List nodeIds}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSelectNodes(
            scopePath: scopePath, nodeIds: nodeIds);

void toggleNodesSelection(
        {required Uint64List scopePath, required Uint64List nodeIds}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiToggleNodesSelection(
            scopePath: scopePath, nodeIds: nodeIds);

Uint64List getSelectedNodeIds() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetSelectedNodeIds();

void moveSelectedNodes(
        {required Uint64List scopePath,
        required double deltaX,
        required double deltaY}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiMoveSelectedNodes(
            scopePath: scopePath, deltaX: deltaX, deltaY: deltaY);

/// Called by Flutter when a node drag begins. Captures current positions for
/// undo coalescing. `scope_path` identifies the body whose nodes are being
/// dragged (empty = top-level); body-scope drags coalesce into a single
/// scope-aware `MoveNodesCommand`. See `doc/design_zones_ui.md` §"Undo/redo".
void beginMoveNodes({required Uint64List scopePath}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiBeginMoveNodes(
        scopePath: scopePath);

/// Called by Flutter when a node drag ends. Creates a single MoveNodesCommand.
/// The target scope is recorded in the pending move captured by
/// `begin_move_nodes`, so `scope_path` here is informational only.
void endMoveNodes({required Uint64List scopePath}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiEndMoveNodes(
        scopePath: scopePath);

/// Undo the last command. Returns true if an undo was performed.
bool undo() =>
    RustLib.instance.api.crateApiStructureDesignerStructureDesignerApiUndo();

/// Redo the last undone command. Returns true if a redo was performed.
bool redo() =>
    RustLib.instance.api.crateApiStructureDesignerStructureDesignerApiRedo();

/// Returns true if there is a command that can be undone.
bool canUndo() =>
    RustLib.instance.api.crateApiStructureDesignerStructureDesignerApiCanUndo();

/// Returns true if there is a command that can be redone.
bool canRedo() =>
    RustLib.instance.api.crateApiStructureDesignerStructureDesignerApiCanRedo();

/// Returns the description of the command that would be undone, or null if nothing to undo.
String? undoDescription() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiUndoDescription();

/// Returns the description of the command that would be redone, or null if nothing to redo.
String? redoDescription() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiRedoDescription();

bool toggleWireSelection(
        {required Uint64List scopePath,
        required BigInt sourceNodeId,
        required int sourceOutputPinIndex,
        required BigInt destinationNodeId,
        required BigInt destinationArgumentIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiToggleWireSelection(
            scopePath: scopePath,
            sourceNodeId: sourceNodeId,
            sourceOutputPinIndex: sourceOutputPinIndex,
            destinationNodeId: destinationNodeId,
            destinationArgumentIndex: destinationArgumentIndex);

bool addWireToSelection(
        {required Uint64List scopePath,
        required BigInt sourceNodeId,
        required int sourceOutputPinIndex,
        required BigInt destinationNodeId,
        required BigInt destinationArgumentIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiAddWireToSelection(
            scopePath: scopePath,
            sourceNodeId: sourceNodeId,
            sourceOutputPinIndex: sourceOutputPinIndex,
            destinationNodeId: destinationNodeId,
            destinationArgumentIndex: destinationArgumentIndex);

List<WireView> getSelectedWires() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetSelectedWires();

void addNodesToSelection(
        {required Uint64List scopePath, required Uint64List nodeIds}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiAddNodesToSelection(
            scopePath: scopePath, nodeIds: nodeIds);

void selectWires({required List<WireIdentifier> wires}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSelectWires(wires: wires);

void addWiresToSelection({required List<WireIdentifier> wires}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiAddWiresToSelection(
            wires: wires);

void toggleWiresSelection({required List<WireIdentifier> wires}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiToggleWiresSelection(
            wires: wires);

void selectNodesAndWires(
        {required Uint64List scopePath,
        required Uint64List nodeIds,
        required List<WireIdentifier> wires}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSelectNodesAndWires(
            scopePath: scopePath, nodeIds: nodeIds, wires: wires);

void addNodesAndWiresToSelection(
        {required Uint64List scopePath,
        required Uint64List nodeIds,
        required List<WireIdentifier> wires}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiAddNodesAndWiresToSelection(
            scopePath: scopePath, nodeIds: nodeIds, wires: wires);

void toggleNodesAndWiresSelection(
        {required Uint64List scopePath,
        required Uint64List nodeIds,
        required List<WireIdentifier> wires}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiToggleNodesAndWiresSelection(
            scopePath: scopePath, nodeIds: nodeIds, wires: wires);

APIExtrudeData? getExtrudeData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetExtrudeData(
            scopePath: scopePath, nodeId: nodeId);

APIIVec3? getExtrudeDrawingPlaneMillerDirection({required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetExtrudeDrawingPlaneMillerDirection(
            nodeId: nodeId);

APIIntData? getIntData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetIntData(
            scopePath: scopePath, nodeId: nodeId);

/// Reads the `schema` property of a `record_construct` node — the name of
/// the record type def its pin layout is bound to. An empty string means
/// "no schema chosen yet". Returns `None` if the node does not exist or is
/// not a `record_construct`.
APIRecordSchemaData? getRecordConstructData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetRecordConstructData(
            scopePath: scopePath, nodeId: nodeId);

/// Reads the `schema` property of a `record_destructure` node — same shape
/// and semantics as `get_record_construct_data`.
APIRecordSchemaData? getRecordDestructureData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetRecordDestructureData(
            scopePath: scopePath, nodeId: nodeId);

/// Reads the `target` property of a `product` node. Surfaced through
/// `APIRecordSchemaData` (the API's `schema` field carries the target's
/// def-name, since the Flutter dropdown is the same widget).
APIRecordSchemaData? getProductData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetProductData(
            scopePath: scopePath, nodeId: nodeId);

APIStringData? getStringData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetStringData(
            scopePath: scopePath, nodeId: nodeId);

APIBoolData? getBoolData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetBoolData(
            scopePath: scopePath, nodeId: nodeId);

APIPrintData? getPrintData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetPrintData(
            scopePath: scopePath, nodeId: nodeId);

APIFloatData? getFloatData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetFloatData(
            scopePath: scopePath, nodeId: nodeId);

APIIVec2Data? getIvec2Data(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetIvec2Data(
            scopePath: scopePath, nodeId: nodeId);

APIIVec3Data? getIvec3Data(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetIvec3Data(
            scopePath: scopePath, nodeId: nodeId);

APISupercellData? getSupercellData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetSupercellData(
            scopePath: scopePath, nodeId: nodeId);

APIIMat2RowsData? getImat2RowsData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetImat2RowsData(
            scopePath: scopePath, nodeId: nodeId);

APIIMat2ColsData? getImat2ColsData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetImat2ColsData(
            scopePath: scopePath, nodeId: nodeId);

APIIMat2DiagData? getImat2DiagData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetImat2DiagData(
            scopePath: scopePath, nodeId: nodeId);

APIPlaneTilingVectorsData? getPlaneTilingVectorsData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetPlaneTilingVectorsData(
            scopePath: scopePath, nodeId: nodeId);

APIIMat3RowsData? getImat3RowsData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetImat3RowsData(
            scopePath: scopePath, nodeId: nodeId);

APIIMat3ColsData? getImat3ColsData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetImat3ColsData(
            scopePath: scopePath, nodeId: nodeId);

APIIMat3DiagData? getImat3DiagData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetImat3DiagData(
            scopePath: scopePath, nodeId: nodeId);

APIMat3RowsData? getMat3RowsData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetMat3RowsData(
            scopePath: scopePath, nodeId: nodeId);

APIMat3ColsData? getMat3ColsData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetMat3ColsData(
            scopePath: scopePath, nodeId: nodeId);

APIMat3DiagData? getMat3DiagData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetMat3DiagData(
            scopePath: scopePath, nodeId: nodeId);

APIRangeData? getRangeData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetRangeData(
            scopePath: scopePath, nodeId: nodeId);

APIVec2Data? getVec2Data(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetVec2Data(
            scopePath: scopePath, nodeId: nodeId);

APIVec3Data? getVec3Data(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetVec3Data(
            scopePath: scopePath, nodeId: nodeId);

APIRectData? getRectData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetRectData(
            scopePath: scopePath, nodeId: nodeId);

APIRegPolyData? getRegPolyData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetRegPolyData(
            scopePath: scopePath, nodeId: nodeId);

APICircleData? getCircleData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetCircleData(
            scopePath: scopePath, nodeId: nodeId);

APIHalfPlaneData? getHalfPlaneData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetHalfPlaneData(
            scopePath: scopePath, nodeId: nodeId);

APICuboidData? getCuboidData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetCuboidData(
            scopePath: scopePath, nodeId: nodeId);

APIAtomCutData? getAtomCutData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetAtomCutData(
            scopePath: scopePath, nodeId: nodeId);

APIApplyDiffData? getApplyDiffData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetApplyDiffData(
            scopePath: scopePath, nodeId: nodeId);

APIAtomComposeDiffData? getAtomComposediffData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetAtomComposediffData(
            scopePath: scopePath, nodeId: nodeId);

APIImportXYZData? getImportXyzData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetImportXyzData(
            scopePath: scopePath, nodeId: nodeId);

APIExportAtomsData? getExportAtomsData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetExportAtomsData(
            scopePath: scopePath, nodeId: nodeId);

/// The supported atom-export formats, a thin projection of
/// `AtomExportFormat::ALL`. The `export_atoms` editor's format indicator and the
/// shared format-chooser dialog are built from this list, so a new format added
/// in Rust surfaces in the UI with no Flutter edits.
List<APIAtomExportFormat> getAtomExportFormats() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetAtomExportFormats();

APISphereData? getSphereData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetSphereData(
            scopePath: scopePath, nodeId: nodeId);

APIHalfSpaceData? getHalfSpaceData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetHalfSpaceData(
            scopePath: scopePath, nodeId: nodeId);

APIDrawingPlaneData? getDrawingPlaneData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetDrawingPlaneData(
            scopePath: scopePath, nodeId: nodeId);

APIGeoTransData? getGeoTransData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetGeoTransData(
            scopePath: scopePath, nodeId: nodeId);

APILatticeSymopData? getLatticeSymopData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetLatticeSymopData(
            scopePath: scopePath, nodeId: nodeId);

APIStructureMoveData? getStructureMoveData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetStructureMoveData(
            scopePath: scopePath, nodeId: nodeId);

APIStructureRotData? getStructureRotData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetStructureRotData(
            scopePath: scopePath, nodeId: nodeId);

APIFreeMoveData? getFreeMoveData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetFreeMoveData(
            scopePath: scopePath, nodeId: nodeId);

APIFreeSphereData? getFreeSphereData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetFreeSphereData(
            scopePath: scopePath, nodeId: nodeId);

APIFreeCircleData? getFreeCircleData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetFreeCircleData(
            scopePath: scopePath, nodeId: nodeId);

APIFreeRotData? getFreeRotData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetFreeRotData(
            scopePath: scopePath, nodeId: nodeId);

APIEditAtomData? getEditAtomData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetEditAtomData(
            scopePath: scopePath, nodeId: nodeId);

APIAtomEditData? getAtomEditData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetAtomEditData(
            scopePath: scopePath, nodeId: nodeId);

APIParameterData? getParameterData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetParameterData(
            scopePath: scopePath, nodeId: nodeId);

APIExprData? getExprData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetExprData(
            scopePath: scopePath, nodeId: nodeId);

APIMapData? getMapData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetMapData(
            scopePath: scopePath, nodeId: nodeId);

APIFilterData? getFilterData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetFilterData(
            scopePath: scopePath, nodeId: nodeId);

APIForeachData? getForeachData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetForeachData(
            scopePath: scopePath, nodeId: nodeId);

APIZipWithData? getZipWithData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetZipWithData(
            scopePath: scopePath, nodeId: nodeId);

APISwitchData? getSwitchData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetSwitchData(
            scopePath: scopePath, nodeId: nodeId);

APIPatchBuildData? getPatchBuildData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetPatchBuildData(
            scopePath: scopePath, nodeId: nodeId);

APIPatchLatticeFillData? getPatchLatticefillData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetPatchLatticefillData(
            scopePath: scopePath, nodeId: nodeId);

APICollectData? getCollectData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetCollectData(
            scopePath: scopePath, nodeId: nodeId);

APIArrayAtData? getArrayAtData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetArrayAtData(
            scopePath: scopePath, nodeId: nodeId);

APIIfData? getIfData({required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api.crateApiStructureDesignerStructureDesignerApiGetIfData(
        scopePath: scopePath, nodeId: nodeId);

APIFoldData? getFoldData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetFoldData(
            scopePath: scopePath, nodeId: nodeId);

APIClosureData? getClosureData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetClosureData(
            scopePath: scopePath, nodeId: nodeId);

APIApplyData? getApplyData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetApplyData(
            scopePath: scopePath, nodeId: nodeId);

APISequenceData? getSequenceData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetSequenceData(
            scopePath: scopePath, nodeId: nodeId);

APIMotifData? getMotifData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetMotifData(
            scopePath: scopePath, nodeId: nodeId);

void setIntData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIIntData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetIntData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setStringData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIStringData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetStringData(
            scopePath: scopePath, nodeId: nodeId, data: data);

/// Writes the `schema` property of a `record_construct` node. After the
/// write, the node-network refresh re-runs the registry-aware cache
/// populator, which rebuilds the per-field input pin layout from the chosen
/// def. An empty string clears the schema. Preserves any existing
/// `literal_values` — entries whose keys no longer match a current field of
/// the new def are inert (see `RecordConstructData::literal_values`).
void setRecordConstructData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIRecordSchemaData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetRecordConstructData(
            scopePath: scopePath, nodeId: nodeId, data: data);

/// Writes the `schema` property of a `record_destructure` node. Same
/// post-write behavior as `set_record_construct_data` — pin layout is
/// re-derived from the chosen def, dangling references leave the node with
/// a placeholder layout and broken downstream wires.
void setRecordDestructureData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIRecordSchemaData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetRecordDestructureData(
            scopePath: scopePath, nodeId: nodeId, data: data);

/// Writes the `target` property of a `product` node. The API's `schema`
/// field is mapped onto the underlying `ProductData.target`. After the
/// write, the registry-aware cache populator rebuilds the per-field
/// `Array[FieldType]` input pins and the `Array[Record(Named(target))]`
/// output pin from the chosen def.
void setProductData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIRecordSchemaData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetProductData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setBoolData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIBoolData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetBoolData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setPrintData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIPrintData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetPrintData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setFloatData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIFloatData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetFloatData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setVec2Data(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIVec2Data data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetVec2Data(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setVec3Data(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIVec3Data data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetVec3Data(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setIvec2Data(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIIVec2Data data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetIvec2Data(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setIvec3Data(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIIVec3Data data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetIvec3Data(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setSupercellData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APISupercellData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetSupercellData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setImat2RowsData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIIMat2RowsData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetImat2RowsData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setImat2ColsData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIIMat2ColsData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetImat2ColsData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setImat2DiagData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIIMat2DiagData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetImat2DiagData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setPlaneTilingVectorsData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIPlaneTilingVectorsData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetPlaneTilingVectorsData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setImat3RowsData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIIMat3RowsData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetImat3RowsData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setImat3ColsData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIIMat3ColsData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetImat3ColsData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setImat3DiagData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIIMat3DiagData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetImat3DiagData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setMat3RowsData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIMat3RowsData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetMat3RowsData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setMat3ColsData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIMat3ColsData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetMat3ColsData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setMat3DiagData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIMat3DiagData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetMat3DiagData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setRangeData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIRangeData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetRangeData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setRectData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIRectData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetRectData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setRegPolyData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIRegPolyData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetRegPolyData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setCircleData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APICircleData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetCircleData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setHalfPlaneData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIHalfPlaneData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetHalfPlaneData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setExtrudeData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIExtrudeData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetExtrudeData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setCuboidData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APICuboidData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetCuboidData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setSphereData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APISphereData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetSphereData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setHalfSpaceData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIHalfSpaceData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetHalfSpaceData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setDrawingPlaneData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIDrawingPlaneData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetDrawingPlaneData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setGeoTransData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIGeoTransData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetGeoTransData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setLatticeSymopData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APILatticeSymopData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetLatticeSymopData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setStructureMoveData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIStructureMoveData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetStructureMoveData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setStructureRotData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIStructureRotData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetStructureRotData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setFreeMoveData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIFreeMoveData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetFreeMoveData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setFreeSphereData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIFreeSphereData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetFreeSphereData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setFreeCircleData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIFreeCircleData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetFreeCircleData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setFreeRotData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIFreeRotData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetFreeRotData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setAtomCutData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIAtomCutData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetAtomCutData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setApplyDiffData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIApplyDiffData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetApplyDiffData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setAtomComposediffData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIAtomComposeDiffData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetAtomComposediffData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setImportXyzData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIImportXYZData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetImportXyzData(
            scopePath: scopePath, nodeId: nodeId, data: data);

APIImportCIFData? getImportCifData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetImportCifData(
            scopePath: scopePath, nodeId: nodeId);

void setImportCifData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIImportCIFData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetImportCifData(
            scopePath: scopePath, nodeId: nodeId, data: data);

APIInferBondsData? getInferBondsData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetInferBondsData(
            scopePath: scopePath, nodeId: nodeId);

void setInferBondsData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIInferBondsData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetInferBondsData(
            scopePath: scopePath, nodeId: nodeId, data: data);

APIAtomReplaceData? getAtomReplaceData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetAtomReplaceData(
            scopePath: scopePath, nodeId: nodeId);

void setAtomReplaceData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIAtomReplaceData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetAtomReplaceData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setExportAtomsData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIExportAtomsData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetExportAtomsData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setParameterData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIParameterData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetParameterData(
            scopePath: scopePath, nodeId: nodeId, data: data);

/// Returns `None` if `node_id` is not a custom node (its `node_type_name` is
/// not a key in `registry.node_networks`). Returns `Some(vec)` — possibly
/// empty — for a custom node, listing only its simple-typed parameters in pin
/// order.
///
/// Runs through `with_mut_cad_instance`: resolving each parameter's default
/// (`resolve_parameter_default`) evaluates the subnetwork and needs `&mut`.
List<APILiteralField>? getCustomNodeParams(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetCustomNodeParams(
            scopePath: scopePath, nodeId: nodeId);

/// Inserts/updates `literal_values[param_name]` on a custom node. Goes through
/// `set_node_network_data`, so it gets the existing `SetNodeData` undo command
/// and `refresh_structure_designer_auto` for free.
void setCustomNodeLiteral(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required String paramName,
        required APILiteralValue value}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetCustomNodeLiteral(
            scopePath: scopePath,
            nodeId: nodeId,
            paramName: paramName,
            value: value);

/// Removes `literal_values[param_name]` from a custom node. Same
/// `set_node_network_data` path as `set_custom_node_literal`.
void clearCustomNodeLiteral(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required String paramName}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiClearCustomNodeLiteral(
            scopePath: scopePath, nodeId: nodeId, paramName: paramName);

/// Returns `None` if `node_id` is not a `record_construct` node, or if its
/// chosen `schema` is empty / not in the registry. Returns `Some(vec)` —
/// possibly empty — listing only the def's simple-typed fields, in authored
/// field order.
///
/// Pure read — `&self`, no subnetwork evaluation. Safe to call on every
/// panel rebuild.
List<APILiteralField>? getRecordConstructFields(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetRecordConstructFields(
            scopePath: scopePath, nodeId: nodeId);

/// Inserts/updates `RecordConstructData.literal_values[field_name]`. Routes
/// through `set_node_network_data`, picking up the existing `SetNodeData`
/// undo command and `refresh_structure_designer_auto` for free.
void setRecordConstructLiteral(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required String fieldName,
        required APILiteralValue value}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetRecordConstructLiteral(
            scopePath: scopePath,
            nodeId: nodeId,
            fieldName: fieldName,
            value: value);

/// Removes `RecordConstructData.literal_values[field_name]`. Same
/// `set_node_network_data` path as `set_record_construct_literal`.
void clearRecordConstructLiteral(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required String fieldName}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiClearRecordConstructLiteral(
            scopePath: scopePath, nodeId: nodeId, fieldName: fieldName);

void setMapData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIMapData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetMapData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setFilterData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIFilterData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetFilterData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setForeachData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIForeachData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetForeachData(
            scopePath: scopePath, nodeId: nodeId, data: data);

/// Whole-list lane + output-type edit on a `zip_with` node (the positional id
/// merge). Delegates to `StructureDesigner::set_zip_with_data` so the shared
/// `NodeStructureEditCommand` undo capture (whole-network snapshots covering the
/// wire fallout) is used — the API layer adds no undo logic of its own. Lane
/// ids are managed Rust-side and never cross the API.
void setZipWithData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIZipWithData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetZipWithData(
            scopePath: scopePath, nodeId: nodeId, data: data);

/// Id-accurate removal of one specific `zip_with` lane (the property panel's
/// per-lane delete button). Surviving lanes keep their hidden stable ids so
/// external wires follow them while the `xs{i}` labels renumber; body wires to
/// the removed `element{i}` are dropped and later ones decremented at mutation
/// time. Delegates to `StructureDesigner::remove_zip_with_lane` (shared undo).
/// A bare lane-type-list setter can only express the positional merge, so the
/// id-accurate removal needs its own entry point.
void removeZipWithLane(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required BigInt laneIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiRemoveZipWithLane(
            scopePath: scopePath, nodeId: nodeId, laneIndex: laneIndex);

/// Whole-data edit on a `switch` node (selector type, value type, and case
/// list, `doc/design_switch_node.md` Phase 4). Case values arrive as the
/// editor's text fields and are parsed here into the selector domain — a field
/// that is not a valid integer under an Int selector is reported back through
/// the `APIResult` so the panel can display it inline (nothing is mutated).
/// Otherwise delegates to `StructureDesigner::set_switch_data`, which performs
/// the value-keyed id merge and pushes the shared `NodeStructureEditCommand`
/// undo capture — the API layer adds no undo logic and never sees the hidden
/// case ids.
APIResult setSwitchData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APISwitchData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetSwitchData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setPatchBuildData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIPatchBuildData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetPatchBuildData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setPatchLatticefillData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIPatchLatticeFillData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetPatchLatticefillData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setCollectData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APICollectData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetCollectData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setArrayAtData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIArrayAtData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetArrayAtData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setIfData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIIfData data}) =>
    RustLib.instance.api.crateApiStructureDesignerStructureDesignerApiSetIfData(
        scopePath: scopePath, nodeId: nodeId, data: data);

void setFoldData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIFoldData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetFoldData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setClosureData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIClosureData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetClosureData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setApplyData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIApplyData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetApplyData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void setSequenceData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APISequenceData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetSequenceData(
            scopePath: scopePath, nodeId: nodeId, data: data);

APIResult setExprData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIExprData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetExprData(
            scopePath: scopePath, nodeId: nodeId, data: data);

APIResult setMotifData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIMotifData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetMotifData(
            scopePath: scopePath, nodeId: nodeId, data: data);

APIMaterializeData? getMaterializeData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetMaterializeData(
            scopePath: scopePath, nodeId: nodeId);

APIResult setMaterializeData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIMaterializeData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetMaterializeData(
            scopePath: scopePath, nodeId: nodeId, data: data);

APIMotifSubData? getMotifSubData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetMotifSubData(
            scopePath: scopePath, nodeId: nodeId);

APIResult setMotifSubData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APIMotifSubData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetMotifSubData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void deleteSelected({required Uint64List scopePath}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiDeleteSelected(
        scopePath: scopePath);

/// Set the return node of the active *top-level* network (a body has no
/// return — its outputs flow through the HOF's zone-output pins). Per
/// `doc/design_zones_ui.md` §"Mutation APIs grow a `scope_path` parameter",
/// `scope_path` is plumbed for shape but must be empty.
bool setReturnNodeId({required Uint64List scopePath, BigInt? nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetReturnNodeId(
            scopePath: scopePath, nodeId: nodeId);

APIResult saveNodeNetworksAs({required String filePath}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSaveNodeNetworksAs(
        filePath: filePath);

APIResult saveNodeNetworks() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSaveNodeNetworks();

bool isDesignDirty() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiIsDesignDirty();

String? getDesignFilePath() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetDesignFilePath();

List<String> getRecentFiles() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetRecentFiles();

APIResult loadNodeNetworks({required String filePath}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiLoadNodeNetworks(
        filePath: filePath);

/// Creates a new empty project, clearing all networks and resetting state.
///
/// This is equivalent to File > New:
/// - Clears all networks
/// - Creates a fresh "Main" network
/// - Clears the file path
/// - Clears the dirty flag
void newProject() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiNewProject();

/// Creates a new project in direct editing mode with a single atom_edit node.
void newProjectDirectEditing() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiNewProjectDirectEditing();

/// Returns the current direct editing mode state.
bool getDirectEditingMode() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetDirectEditingMode();

/// Sets direct editing mode and marks the design as dirty.
void setDirectEditingMode({required bool mode}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSetDirectEditingMode(
        mode: mode);

/// Returns whether the current state allows switching to direct editing mode.
bool canSwitchToDirectEditingMode() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiCanSwitchToDirectEditingMode();

/// Imports an XYZ file into the active atom_edit node's diff layer.
/// Atoms and bonds are merged directly as pure additions (incremental import).
/// Returns an empty string on success, or an error message on failure.
String importXyzIntoAtomEdit({required String filePath}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiImportXyzIntoAtomEdit(
        filePath: filePath);

/// Returns the number of node networks in the current project.
int getNetworkCount() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetNetworkCount();

bool isNodeTypeActive({required String nodeType}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiIsNodeTypeActive(
        nodeType: nodeType);

String getApiDataTypeDisplayName({required APIDataType apiDataType}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetApiDataTypeDisplayName(
            apiDataType: apiDataType);

StructureDesignerPreferences? getStructureDesignerPreferences() => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiGetStructureDesignerPreferences();

void setStructureDesignerPreferences(
        {required StructureDesignerPreferences preferences}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetStructureDesignerPreferences(
            preferences: preferences);

APIResult exportVisibleAtomicStructures({required String filePath}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiExportVisibleAtomicStructures(
        filePath: filePath);

APILatticeVecsData? getLatticeVecsData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetLatticeVecsData(
            scopePath: scopePath, nodeId: nodeId);

void setLatticeVecsData(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required APILatticeVecsData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetLatticeVecsData(
            scopePath: scopePath, nodeId: nodeId, data: data);

void validateActiveNetwork() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiValidateActiveNetwork();

/// Run atomCAD in headless CLI mode with a single configuration
APIResult runCliSingle({required CliConfig config}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiRunCliSingle(config: config);

/// Run atomCAD in headless CLI batch mode
APIResult runCliBatch({required BatchCliConfig config}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiRunCliBatch(config: config);

/// Set the stored body width/height of an HOF (zone-owning) node, identified
/// by the body the resize applies to. `scope_path` is the chain of HOF node
/// IDs leading to the body's owner — empty means the active top-level network,
/// `[hof_id]` means the body owned by `hof_id` at the top level, deeper paths
/// address bodies nested inside bodies. `hof_node_id` is the HOF whose stored
/// body size is changing (located inside the scope's body).
///
/// Minimums clamp at 100×60 logical pixels so the body region is always large
/// enough to render its inner pins. The body's *rendered* size is
/// `max(stored, content_bbox + padding)` (zones UI design doc §"Body sizing"),
/// so the user can shrink stored size down to the clamp regardless of content.
///
/// Phase U3 lands the API; the drag handles that drive it land alongside body
/// content rendering. No undo command yet — that's tracked in U4 alongside
/// node-move begin/end coalescing.
void setZoneSize(
        {required Uint64List scopePath,
        required BigInt hofNodeId,
        required double width,
        required double height}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetZoneSize(
            scopePath: scopePath,
            hofNodeId: hofNodeId,
            width: width,
            height: height);

/// Called when an HOF body resize drag begins. Captures the body's pre-drag
/// dimensions so the matching `end_zone_resize` records a single coalesced
/// `SetZoneSizeCommand` (mirrors `begin_move_nodes`). See
/// `doc/design_zones_ui.md` §"Resize handles".
void beginZoneResize(
        {required Uint64List scopePath, required BigInt hofNodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiBeginZoneResize(
            scopePath: scopePath, hofNodeId: hofNodeId);

/// Called when an HOF body resize drag ends. Pushes one undoable
/// `SetZoneSizeCommand` if the body changed size.
void endZoneResize() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiEndZoneResize();

/// Set an HOF node's collapse mode (Auto / Collapsed / Expanded). Thin wrapper;
/// the mutation + undo command live on `StructureDesigner::set_collapse_mode`.
/// `scope_path` identifies the (possibly nested) body the HOF lives in. No-op
/// for non-collapsable nodes. See `doc/design_hof_node_collapse.md`.
void setCollapseMode(
        {required Uint64List scopePath,
        required BigInt hofNodeId,
        required APICollapseMode mode}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetCollapseMode(
            scopePath: scopePath, hofNodeId: hofNodeId, mode: mode);

/// Resize a comment node.
/// This performs a direct mutation without undo — call begin_edit_comment_node/end_edit_comment_node
/// around the resize drag to get a single coalesced undo entry.
void resizeCommentNode(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required double width,
        required double height}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiResizeCommentNode(
            scopePath: scopePath, nodeId: nodeId, width: width, height: height);

/// Update a comment node's label and text.
/// This performs a direct mutation without undo — call begin_edit_comment_node/end_edit_comment_node
/// around the editing session to get a single coalesced undo entry.
void updateCommentNode(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required String label,
        required String text}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiUpdateCommentNode(
            scopePath: scopePath, nodeId: nodeId, label: label, text: text);

/// Called when a comment node text field gains focus or resize drag begins.
/// Captures a snapshot for undo coalescing.
void beginEditCommentNode(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiBeginEditCommentNode(
            scopePath: scopePath, nodeId: nodeId);

/// Called when a comment node text field loses focus or resize drag ends.
/// Pushes a single undo command if the comment data changed.
void endEditCommentNode() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiEndEditCommentNode();

/// Get comment node data for property panel editing
APICommentData? getCommentData(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetCommentData(
            scopePath: scopePath, nodeId: nodeId);

/// Evaluate a node and return its result string.
///
/// # Arguments
/// * `node_identifier` - Either a numeric node ID or the node's custom name
/// * `verbose` - If true, return detailed output for complex types
///
/// # Returns
/// * `Ok(APINodeEvaluationResult)` - The evaluation result
/// * `Err(String)` - If node not found or evaluation fails
APINodeEvaluationResult evaluateNode(
        {required String nodeIdentifier, required bool verbose}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiEvaluateNode(
            nodeIdentifier: nodeIdentifier, verbose: verbose);

/// Run an explicit Execute pass on a node — the right-click → Execute action
/// in the node-graph UI. Sets `execute = true` for one evaluation pass on the
/// targeted node, which is what gates side-effect nodes (`export_atoms`,
/// `foreach`, future effect nodes) to actually fire. See
/// `doc/design_node_execution.md` (Phase 3 — Triggering execute mode from
/// the UI).
///
/// # Arguments
/// * `network_name` - Network containing the node to execute
/// * `node_id` - Numeric node id of the node to execute
///
/// # Returns
/// * `Ok(APIExecuteResult)` on a successful pass (with `ok` indicating whether
///   the node itself produced an error)
/// * `Err(String)` on structural problems (missing network/node, invalid network)
APIExecuteResult executeNode(
        {required String networkName,
        required Uint64List scopePath,
        required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiExecuteNode(
            networkName: networkName, scopePath: scopePath, nodeId: nodeId);

/// Drain and return the accumulated print-log entries.
///
/// The Flutter Console panel calls this at a sensible cadence (after each
/// evaluation triggered through the model layer, plus on Console-panel open).
/// Drain-on-read prevents the buffer from growing indefinitely as long as the
/// panel is occasionally opened. See `doc/design_node_execution.md`
/// (Phase 4 — FFI).
List<APIPrintLogEntry> takePrintLog() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiTakePrintLog();

/// Clear all entries in the print-log buffer (Console panel "Clear" button).
void clearPrintLog() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiClearPrintLog();

/// Drain the parameter-id repair messages from the most recent project load
/// (F6 of `doc/design_parameter_wire_stability.md`). Returns an empty list when
/// the loaded project needed no repair. The UI reads this once right after
/// `load_node_networks` to decide whether to show the "auto-repaired" modal.
List<String> takeLoadParamIdRepairs() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiTakeLoadParamIdRepairs();

/// Apply auto-layout to the active node network.
///
/// This function recomputes positions for all nodes in the active network
/// using the user's preferred layout algorithm from preferences.
///
/// # Behavior
/// - Uses the layout algorithm specified in StructureDesignerPreferences
/// - Reorganizes all nodes in the active network for improved readability
/// - Automatically refreshes the UI after layout
void layoutActiveNetwork() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiLayoutActiveNetwork();

/// Get information about whether/how the current selection can be factored into a subnetwork.
///
/// Returns information that can be used to populate the "Factor into Subnetwork" dialog,
/// including suggested names for the subnetwork and its parameters.
FactorSelectionInfo getFactorSelectionInfo() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetFactorSelectionInfo();

/// Factor the current selection into a new subnetwork.
///
/// Creates a new custom node type from the selected nodes and replaces
/// the selection with an instance of that node type.
///
/// # Arguments
/// * `request` - The factoring request containing the subnetwork name and parameter names
///
/// # Returns
/// A result indicating success or failure, with the new node ID on success
FactorSelectionResult factorSelectionIntoSubnetwork(
        {required FactorSelectionRequest request}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiFactorSelectionIntoSubnetwork(
            request: request);

/// Whether the node at `(scope_path, node_id)` can be inlined — i.e. it is a
/// custom-network instance (built-ins, HOFs, `apply`, `closure` are not custom
/// types and so are rejected). Used to gate the context-menu item.
bool canInlineNode({required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiCanInlineNode(
            scopePath: scopePath, nodeId: nodeId);

/// Inline a custom-network instance: replace the node at `(scope_path, node_id)`
/// with a copy of its custom network's contents, spliced into the parent
/// network (or zone body) in place. The named definition is left untouched.
///
/// See `doc/design_inline_custom_node.md`.
InlineResult inlineCustomNode(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiInlineCustomNode(
            scopePath: scopePath, nodeId: nodeId);

/// Whether the node at `(scope_path, node_id)` can be converted to a closure —
/// i.e. it is a custom-network instance used as a function (or unconsumed), with
/// a return node. Used to gate the context-menu item.
/// See `doc/design_closure_network_conversion.md` (Direction A).
bool canConvertInstanceToClosure(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiCanConvertInstanceToClosure(
            scopePath: scopePath, nodeId: nodeId);

/// Convert a custom-network instance node into a `closure` node
/// (*Network → Closure*): replaces the instance `I` at `(scope_path, node_id)`
/// with a `closure` node `C` whose inline body is a copy of `I`'s network. `I`'s
/// wired input pins become captures in the body; its unwired input pins become
/// the closure's parameters. See `doc/design_closure_network_conversion.md`.
ConversionResult convertInstanceToClosure(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiConvertInstanceToClosure(
            scopePath: scopePath, nodeId: nodeId);

/// Whether the node at `(scope_path, node_id)` can be extracted to a network —
/// i.e. it is a `closure` node with a result wire. Used to gate the
/// context-menu item. See `doc/design_closure_network_conversion.md`
/// (Direction B).
bool canExtractClosureToNetwork(
        {required Uint64List scopePath, required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiCanExtractClosureToNetwork(
            scopePath: scopePath, nodeId: nodeId);

/// Extract a `closure` node into a new named custom network
/// (*Closure → Network*): lifts the closure `C`'s inline body into a fresh
/// standalone network `N` (with parameter nodes for both the closure's
/// parameters and its captures) and replaces `C` with an instance of `N`, wired
/// so its function pin reproduces `C`. See
/// `doc/design_closure_network_conversion.md`.
ConversionResult extractClosureToNetwork(
        {required Uint64List scopePath,
        required BigInt nodeId,
        required String name}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiExtractClosureToNetwork(
            scopePath: scopePath, nodeId: nodeId, name: name);

/// Promote a node to a parameter.
///
/// Inserts a `parameter` node typed after the given node's output pin 0,
/// wires that pin into the parameter's default input, and rewires every
/// downstream consumer of the source's pin 0 — including a return-node
/// reference — to read from the parameter instead.
APIPromoteToParameterResult promoteNodeToParameter({required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiPromoteNodeToParameter(
            nodeId: nodeId);

bool copySelection({required Uint64List scopePath}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiCopySelection(
        scopePath: scopePath);

Uint64List pasteAtPosition(
        {required Uint64List scopePath,
        required double x,
        required double y}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiPasteAtPosition(
            scopePath: scopePath, x: x, y: y);

bool cutSelection({required Uint64List scopePath}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiCutSelection(
        scopePath: scopePath);

bool hasClipboardContent() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiHasClipboardContent();

/// Serialize the active node network to text format for the text editor tab.
String serializeActiveNetworkToText() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSerializeActiveNetworkToText();

/// Apply text format edits to the active node network (replace mode with position preservation).
APITextEditResult applyTextToActiveNetwork({required String code}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiApplyTextToActiveNetwork(
            code: code);

APIHoveredAtomInfo? queryHoveredAtomInfo(
        {required APIVec3 rayOrigin, required APIVec3 rayDirection}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiQueryHoveredAtomInfo(
            rayOrigin: rayOrigin, rayDirection: rayDirection);

/// Performs a viewport pick for click-to-activate.
///
/// Casts a ray through the scene and determines whether the click should:
/// - Pass through to normal handling (active node hit or no hit)
/// - Activate a different node (unambiguous non-active node hit)
/// - Show a disambiguation popup (overlapping non-active node hits)
APIViewportPickResult viewportPick(
        {required APIVec3 rayOrigin, required APIVec3 rayDirection}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiViewportPick(
            rayOrigin: rayOrigin, rayDirection: rayDirection);

/// Check whether CLI write access is locked for a given network name.
/// Returns true if the network is locked from CLI write access.
bool isCliWriteLocked({required String networkName}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiIsCliWriteLocked(
        networkName: networkName);

/// Set CLI access for a namespace or network name.
/// `allowed = true` means CLI can write, `allowed = false` means CLI is locked out.
/// Setting a rule prunes all descendant rules to keep the map minimal.
void setCliAccess({required String name, required bool allowed}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetCliAccess(
            name: name, allowed: allowed);

/// Get all CLI access rules as a list of (prefix, allowed) pairs.
/// This is used by the Flutter UI to display lock state in the tree view.
List<(String, bool)> getCliAccessRules() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetCliAccessRules();
