// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../common_api_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'structure_designer_api_types.dart';
import 'structure_designer_preferences.dart';

// These functions are ignored because they are not marked as `pub`: `api_data_type_to_data_type`, `crystal_system_to_string`, `data_type_to_api_data_type`

NodeNetworkView? getNodeNetworkView() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetNodeNetworkView();

void moveNode({required BigInt nodeId, required APIVec2 position}) =>
    RustLib.instance.api.crateApiStructureDesignerStructureDesignerApiMoveNode(
        nodeId: nodeId, position: position);

BigInt addNode({required String nodeTypeName, required APIVec2 position}) =>
    RustLib.instance.api.crateApiStructureDesignerStructureDesignerApiAddNode(
        nodeTypeName: nodeTypeName, position: position);

BigInt duplicateNode({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiDuplicateNode(nodeId: nodeId);

bool canConnectNodes(
        {required BigInt sourceNodeId,
        required int sourceOutputPinIndex,
        required BigInt destNodeId,
        required BigInt destParamIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiCanConnectNodes(
            sourceNodeId: sourceNodeId,
            sourceOutputPinIndex: sourceOutputPinIndex,
            destNodeId: destNodeId,
            destParamIndex: destParamIndex);

void connectNodes(
        {required BigInt sourceNodeId,
        required int sourceOutputPinIndex,
        required BigInt destNodeId,
        required BigInt destParamIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiConnectNodes(
            sourceNodeId: sourceNodeId,
            sourceOutputPinIndex: sourceOutputPinIndex,
            destNodeId: destNodeId,
            destParamIndex: destParamIndex);

/// Auto-connects a source pin to the first compatible pin on a target node.
///
/// - `source_node_id`: The node where the wire was dragged from
/// - `source_pin_index`: The pin index on the source node
/// - `source_is_output`: true if dragging from output pin, false if from input pin
/// - `target_node_id`: The newly created node to connect to
///
/// Returns true if a connection was made, false otherwise.
bool autoConnectToNode(
        {required BigInt sourceNodeId,
        required int sourcePinIndex,
        required bool sourceIsOutput,
        required BigInt targetNodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiAutoConnectToNode(
            sourceNodeId: sourceNodeId,
            sourcePinIndex: sourcePinIndex,
            sourceIsOutput: sourceIsOutput,
            targetNodeId: targetNodeId);

/// Returns all compatible pins on the target node for auto-connection.
/// Each element contains (pin_index, pin_name, data_type_string).
/// When source_is_output is true, returns compatible INPUT pins on target.
/// When source_is_output is false, returns the OUTPUT pin if compatible.
List<(int, String, String)> getCompatiblePinsForAutoConnect(
        {required BigInt sourceNodeId,
        required int sourcePinIndex,
        required bool sourceIsOutput,
        required BigInt targetNodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetCompatiblePinsForAutoConnect(
            sourceNodeId: sourceNodeId,
            sourcePinIndex: sourcePinIndex,
            sourceIsOutput: sourceIsOutput,
            targetNodeId: targetNodeId);

List<APINodeCategoryView>? getNodeTypeViews() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetNodeTypeViews();

/// Returns node types that have at least one pin compatible with the given type.
///
/// - `source_type_str`: The data type being dragged (serialized string, e.g., "Geometry", "Float")
/// - `dragging_from_output`: true if dragging from output pin, false if from input pin
///
/// When dragging from OUTPUT: find nodes with compatible INPUT pins
/// When dragging from INPUT: find nodes with compatible OUTPUT pins
List<APINodeCategoryView>? getCompatibleNodeTypes(
        {required String sourceTypeStr, required bool draggingFromOutput}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetCompatibleNodeTypes(
            sourceTypeStr: sourceTypeStr,
            draggingFromOutput: draggingFromOutput);

List<String>? getNodeNetworkNames() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetNodeNetworkNames();

/// Checks if a node type name corresponds to a custom node (i.e., a user-defined node network).
/// Returns false if the CAD instance is not available.
bool isCustomNodeType({required String nodeTypeName}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiIsCustomNodeType(
        nodeTypeName: nodeTypeName);

/// Gets the description of the active node network
String? getActiveNetworkDescription() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetActiveNetworkDescription();

/// Sets the description of the active node network
void setActiveNetworkDescription({required String description}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiSetActiveNetworkDescription(
        description: description);

/// Gets the summary of the active node network
String? getActiveNetworkSummary() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetActiveNetworkSummary();

/// Sets the summary of the active node network
/// Pass None or empty string to clear the summary
void setActiveNetworkSummary({String? summary}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSetActiveNetworkSummary(
        summary: summary);

/// Gets the description of a specific node network
String? getNetworkDescription({required String networkName}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiGetNetworkDescription(
        networkName: networkName);

List<APINetworkWithValidationErrors>? getNodeNetworksWithValidation() => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiGetNodeNetworksWithValidation();

void addNewNodeNetwork() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiAddNewNodeNetwork();

/// Add a node network with a specific name.
/// Returns success/error. Auto-activates the new network.
APIResult addNodeNetworkWithName({required String name}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiAddNodeNetworkWithName(
        name: name);

void setActiveNodeNetwork({required String nodeNetworkName}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiSetActiveNodeNetwork(
        nodeNetworkName: nodeNetworkName);

/// Navigates back in node network history
bool navigateBack() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiNavigateBack();

/// Navigates forward in node network history
bool navigateForward() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiNavigateForward();

/// Checks if we can navigate backward in node network history
bool canNavigateBack() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiCanNavigateBack();

/// Checks if we can navigate forward in node network history
bool canNavigateForward() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiCanNavigateForward();

bool renameNodeNetwork({required String oldName, required String newName}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiRenameNodeNetwork(
            oldName: oldName, newName: newName);

APIResult deleteNodeNetwork({required String networkName}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiDeleteNodeNetwork(
            networkName: networkName);

void setNodeDisplay({required BigInt nodeId, required bool isDisplayed}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetNodeDisplay(
            nodeId: nodeId, isDisplayed: isDisplayed);

bool selectNode({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSelectNode(nodeId: nodeId);

bool selectWire(
        {required BigInt sourceNodeId,
        required int sourceOutputPinIndex,
        required BigInt destinationNodeId,
        required BigInt destinationArgumentIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSelectWire(
            sourceNodeId: sourceNodeId,
            sourceOutputPinIndex: sourceOutputPinIndex,
            destinationNodeId: destinationNodeId,
            destinationArgumentIndex: destinationArgumentIndex);

void clearSelection() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiClearSelection();

bool toggleNodeSelection({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiToggleNodeSelection(
        nodeId: nodeId);

bool addNodeToSelection({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiAddNodeToSelection(
        nodeId: nodeId);

bool selectNodes({required Uint64List nodeIds}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSelectNodes(nodeIds: nodeIds);

void toggleNodesSelection({required Uint64List nodeIds}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiToggleNodesSelection(
        nodeIds: nodeIds);

Uint64List getSelectedNodeIds() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetSelectedNodeIds();

void moveSelectedNodes({required double deltaX, required double deltaY}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiMoveSelectedNodes(
            deltaX: deltaX, deltaY: deltaY);

bool toggleWireSelection(
        {required BigInt sourceNodeId,
        required int sourceOutputPinIndex,
        required BigInt destinationNodeId,
        required BigInt destinationArgumentIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiToggleWireSelection(
            sourceNodeId: sourceNodeId,
            sourceOutputPinIndex: sourceOutputPinIndex,
            destinationNodeId: destinationNodeId,
            destinationArgumentIndex: destinationArgumentIndex);

bool addWireToSelection(
        {required BigInt sourceNodeId,
        required int sourceOutputPinIndex,
        required BigInt destinationNodeId,
        required BigInt destinationArgumentIndex}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiAddWireToSelection(
            sourceNodeId: sourceNodeId,
            sourceOutputPinIndex: sourceOutputPinIndex,
            destinationNodeId: destinationNodeId,
            destinationArgumentIndex: destinationArgumentIndex);

List<WireView> getSelectedWires() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetSelectedWires();

void addNodesToSelection({required Uint64List nodeIds}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiAddNodesToSelection(
        nodeIds: nodeIds);

void selectWires({required List<WireIdentifier> wires}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSelectWires(wires: wires);

void addWiresToSelection({required List<WireIdentifier> wires}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiAddWiresToSelection(
            wires: wires);

void toggleWiresSelection({required List<WireIdentifier> wires}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiToggleWiresSelection(
            wires: wires);

void selectNodesAndWires(
        {required Uint64List nodeIds, required List<WireIdentifier> wires}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSelectNodesAndWires(
            nodeIds: nodeIds, wires: wires);

void addNodesAndWiresToSelection(
        {required Uint64List nodeIds, required List<WireIdentifier> wires}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiAddNodesAndWiresToSelection(
            nodeIds: nodeIds, wires: wires);

void toggleNodesAndWiresSelection(
        {required Uint64List nodeIds, required List<WireIdentifier> wires}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiToggleNodesAndWiresSelection(
            nodeIds: nodeIds, wires: wires);

APIExtrudeData? getExtrudeData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetExtrudeData(
        nodeId: nodeId);

APIIVec3? getExtrudeDrawingPlaneMillerDirection({required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetExtrudeDrawingPlaneMillerDirection(
            nodeId: nodeId);

APIIntData? getIntData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetIntData(nodeId: nodeId);

APIStringData? getStringData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetStringData(nodeId: nodeId);

APIBoolData? getBoolData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetBoolData(nodeId: nodeId);

APIFloatData? getFloatData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetFloatData(nodeId: nodeId);

APIIVec2Data? getIvec2Data({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetIvec2Data(nodeId: nodeId);

APIIVec3Data? getIvec3Data({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetIvec3Data(nodeId: nodeId);

APIRangeData? getRangeData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetRangeData(nodeId: nodeId);

APIVec2Data? getVec2Data({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetVec2Data(nodeId: nodeId);

APIVec3Data? getVec3Data({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetVec3Data(nodeId: nodeId);

APIRectData? getRectData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetRectData(nodeId: nodeId);

APIRegPolyData? getRegPolyData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetRegPolyData(
        nodeId: nodeId);

APICircleData? getCircleData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetCircleData(nodeId: nodeId);

APIHalfPlaneData? getHalfPlaneData({required BigInt nodeId}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiGetHalfPlaneData(
        nodeId: nodeId);

APICuboidData? getCuboidData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetCuboidData(nodeId: nodeId);

APIAtomCutData? getAtomCutData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetAtomCutData(
        nodeId: nodeId);

APIImportXYZData? getImportXyzData({required BigInt nodeId}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiGetImportXyzData(
        nodeId: nodeId);

APIExportXYZData? getExportXyzData({required BigInt nodeId}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiGetExportXyzData(
        nodeId: nodeId);

APISphereData? getSphereData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetSphereData(nodeId: nodeId);

APIHalfSpaceData? getHalfSpaceData({required BigInt nodeId}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiGetHalfSpaceData(
        nodeId: nodeId);

APIDrawingPlaneData? getDrawingPlaneData({required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetDrawingPlaneData(
            nodeId: nodeId);

APIGeoTransData? getGeoTransData({required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetGeoTransData(
            nodeId: nodeId);

APILatticeSymopData? getLatticeSymopData({required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetLatticeSymopData(
            nodeId: nodeId);

APILatticeMoveData? getLatticeMoveData({required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetLatticeMoveData(
            nodeId: nodeId);

APILatticeRotData? getLatticeRotData({required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetLatticeRotData(
            nodeId: nodeId);

APIAtomMoveData? getAtomMoveData({required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetAtomMoveData(
            nodeId: nodeId);

APIAtomRotData? getAtomRotData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetAtomRotData(
        nodeId: nodeId);

APIAtomTransData? getAtomTransData({required BigInt nodeId}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiGetAtomTransData(
        nodeId: nodeId);

APIEditAtomData? getEditAtomData({required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetEditAtomData(
            nodeId: nodeId);

APIParameterData? getParameterData({required BigInt nodeId}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiGetParameterData(
        nodeId: nodeId);

APIExprData? getExprData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetExprData(nodeId: nodeId);

APIMapData? getMapData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetMapData(nodeId: nodeId);

APIMotifData? getMotifData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetMotifData(nodeId: nodeId);

void setIntData({required BigInt nodeId, required APIIntData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetIntData(
            nodeId: nodeId, data: data);

void setStringData({required BigInt nodeId, required APIStringData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetStringData(
            nodeId: nodeId, data: data);

void setBoolData({required BigInt nodeId, required APIBoolData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetBoolData(
            nodeId: nodeId, data: data);

void setFloatData({required BigInt nodeId, required APIFloatData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetFloatData(
            nodeId: nodeId, data: data);

void setVec2Data({required BigInt nodeId, required APIVec2Data data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetVec2Data(
            nodeId: nodeId, data: data);

void setVec3Data({required BigInt nodeId, required APIVec3Data data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetVec3Data(
            nodeId: nodeId, data: data);

void setIvec2Data({required BigInt nodeId, required APIIVec2Data data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetIvec2Data(
            nodeId: nodeId, data: data);

void setIvec3Data({required BigInt nodeId, required APIIVec3Data data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetIvec3Data(
            nodeId: nodeId, data: data);

void setRangeData({required BigInt nodeId, required APIRangeData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetRangeData(
            nodeId: nodeId, data: data);

void setRectData({required BigInt nodeId, required APIRectData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetRectData(
            nodeId: nodeId, data: data);

void setRegPolyData({required BigInt nodeId, required APIRegPolyData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetRegPolyData(
            nodeId: nodeId, data: data);

void setCircleData({required BigInt nodeId, required APICircleData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetCircleData(
            nodeId: nodeId, data: data);

void setHalfPlaneData(
        {required BigInt nodeId, required APIHalfPlaneData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetHalfPlaneData(
            nodeId: nodeId, data: data);

void setExtrudeData({required BigInt nodeId, required APIExtrudeData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetExtrudeData(
            nodeId: nodeId, data: data);

void setCuboidData({required BigInt nodeId, required APICuboidData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetCuboidData(
            nodeId: nodeId, data: data);

void setSphereData({required BigInt nodeId, required APISphereData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetSphereData(
            nodeId: nodeId, data: data);

void setHalfSpaceData(
        {required BigInt nodeId, required APIHalfSpaceData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetHalfSpaceData(
            nodeId: nodeId, data: data);

void setDrawingPlaneData(
        {required BigInt nodeId, required APIDrawingPlaneData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetDrawingPlaneData(
            nodeId: nodeId, data: data);

void setGeoTransData({required BigInt nodeId, required APIGeoTransData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetGeoTransData(
            nodeId: nodeId, data: data);

void setLatticeSymopData(
        {required BigInt nodeId, required APILatticeSymopData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetLatticeSymopData(
            nodeId: nodeId, data: data);

void setLatticeMoveData(
        {required BigInt nodeId, required APILatticeMoveData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetLatticeMoveData(
            nodeId: nodeId, data: data);

void setLatticeRotData(
        {required BigInt nodeId, required APILatticeRotData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetLatticeRotData(
            nodeId: nodeId, data: data);

void setAtomMoveData({required BigInt nodeId, required APIAtomMoveData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetAtomMoveData(
            nodeId: nodeId, data: data);

void setAtomRotData({required BigInt nodeId, required APIAtomRotData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetAtomRotData(
            nodeId: nodeId, data: data);

void setAtomTransData(
        {required BigInt nodeId, required APIAtomTransData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetAtomTransData(
            nodeId: nodeId, data: data);

void setAtomCutData({required BigInt nodeId, required APIAtomCutData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetAtomCutData(
            nodeId: nodeId, data: data);

void setImportXyzData(
        {required BigInt nodeId, required APIImportXYZData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetImportXyzData(
            nodeId: nodeId, data: data);

void setExportXyzData(
        {required BigInt nodeId, required APIExportXYZData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetExportXyzData(
            nodeId: nodeId, data: data);

void setParameterData(
        {required BigInt nodeId, required APIParameterData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetParameterData(
            nodeId: nodeId, data: data);

void setMapData({required BigInt nodeId, required APIMapData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetMapData(
            nodeId: nodeId, data: data);

APIResult setExprData({required BigInt nodeId, required APIExprData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetExprData(
            nodeId: nodeId, data: data);

APIResult setMotifData({required BigInt nodeId, required APIMotifData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetMotifData(
            nodeId: nodeId, data: data);

APIAtomFillData? getAtomFillData({required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetAtomFillData(
            nodeId: nodeId);

APIResult setAtomFillData(
        {required BigInt nodeId, required APIAtomFillData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetAtomFillData(
            nodeId: nodeId, data: data);

void deleteSelected() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiDeleteSelected();

bool setReturnNodeId({BigInt? nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSetReturnNodeId(
        nodeId: nodeId);

APIResult saveNodeNetworksAs({required String filePath}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSaveNodeNetworksAs(
        filePath: filePath);

APIResult saveNodeNetworks() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiSaveNodeNetworks();

bool isDesignDirty() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiIsDesignDirty();

String? getDesignFilePath() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetDesignFilePath();

APIResult loadNodeNetworks({required String filePath}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiLoadNodeNetworks(
        filePath: filePath);

/// Creates a new empty project, clearing all networks and resetting state.
///
/// This is equivalent to File > New:
/// - Clears all networks
/// - Creates a fresh "Main" network
/// - Clears the file path
/// - Clears the dirty flag
void newProject() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiNewProject();

/// Returns the number of node networks in the current project.
int getNetworkCount() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetNetworkCount();

bool isNodeTypeActive({required String nodeType}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiIsNodeTypeActive(
        nodeType: nodeType);

String getApiDataTypeDisplayName({required APIDataType apiDataType}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetApiDataTypeDisplayName(
            apiDataType: apiDataType);

StructureDesignerPreferences? getStructureDesignerPreferences() => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiGetStructureDesignerPreferences();

void setStructureDesignerPreferences(
        {required StructureDesignerPreferences preferences}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetStructureDesignerPreferences(
            preferences: preferences);

APIResult exportVisibleAtomicStructures({required String filePath}) => RustLib
    .instance.api
    .crateApiStructureDesignerStructureDesignerApiExportVisibleAtomicStructures(
        filePath: filePath);

APIUnitCellData? getUnitCellData({required BigInt nodeId}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiGetUnitCellData(
            nodeId: nodeId);

void setUnitCellData({required BigInt nodeId, required APIUnitCellData data}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiSetUnitCellData(
            nodeId: nodeId, data: data);

void validateActiveNetwork() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiValidateActiveNetwork();

/// Run atomCAD in headless CLI mode with a single configuration
APIResult runCliSingle({required CliConfig config}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiRunCliSingle(config: config);

/// Run atomCAD in headless CLI batch mode
APIResult runCliBatch({required BatchCliConfig config}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiRunCliBatch(config: config);

/// Resize a comment node
void resizeCommentNode(
        {required BigInt nodeId,
        required double width,
        required double height}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiResizeCommentNode(
            nodeId: nodeId, width: width, height: height);

/// Update a comment node's label and text
void updateCommentNode(
        {required BigInt nodeId,
        required String label,
        required String text}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiUpdateCommentNode(
            nodeId: nodeId, label: label, text: text);

/// Get comment node data for property panel editing
APICommentData? getCommentData({required BigInt nodeId}) => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiGetCommentData(
        nodeId: nodeId);

/// Evaluate a node and return its result string.
///
/// # Arguments
/// * `node_identifier` - Either a numeric node ID or the node's custom name
/// * `verbose` - If true, return detailed output for complex types
///
/// # Returns
/// * `Ok(APINodeEvaluationResult)` - The evaluation result
/// * `Err(String)` - If node not found or evaluation fails
APINodeEvaluationResult evaluateNode(
        {required String nodeIdentifier, required bool verbose}) =>
    RustLib.instance.api
        .crateApiStructureDesignerStructureDesignerApiEvaluateNode(
            nodeIdentifier: nodeIdentifier, verbose: verbose);

/// Apply auto-layout to the active node network.
///
/// This function recomputes positions for all nodes in the active network
/// using the user's preferred layout algorithm from preferences.
///
/// # Behavior
/// - Uses the layout algorithm specified in StructureDesignerPreferences
/// - Reorganizes all nodes in the active network for improved readability
/// - Automatically refreshes the UI after layout
void layoutActiveNetwork() => RustLib.instance.api
    .crateApiStructureDesignerStructureDesignerApiLayoutActiveNetwork();
